### ISSUE TITLE
[Registration] Account registration button is unthemed

### ISSUE THREAD

**Issue by Xenthys** [mwalbeck/nextcloud-breeze-dark#100]
**Describe the bug**
When on the login page, the register button appears completely white (text + background), thus unreadable.

**To Reproduce**
1. Install and enable the Registration app
2. Install and enable the Breeze Dark theme
3. Log out of Nextcloud to reach the login page
4. See the unthemed button :(

**Expected behavior**
The registration button should match the login button, related to #56 I think.

**Screenshots**
Seen on my own (French) instance: ![screenshot](https://my.stupid.pics/UguxbGD.png)

**Setup**
 - Nextcloud version: 18.0.1
 - Theme version: 18.0.7
 - Browser version: Firefox 73.0.1

**Comment by mwalbeck** [comment]
Thank you for reporting this. A fix has been pushed to master and will be included in the next release.

**Comment by mwalbeck** [comment]
And the new release has just been published.

**Comment by Xenthys** [comment]
I can confirm the registration button is now dark-themed, thanks a lot!
