### ISSUE TITLE
Implement per user theming

### ISSUE THREAD

**Issue by mwalbeck** [mwalbeck/nextcloud-breeze-dark#104]
As noted in #98, allow individual users to enable/disable the theme on a single Nextcloud instance, like is possible with the official dark theme.

**Comment by mwalbeck** [comment]
I have had a proper look and made a plan for the implementation, and I'm about halfway there with the development.

The plan is to have 2 toggles a user specific and a global one. The reason for having a global toggle is to allow for sharing pages and the login page to be styled, basically any page visited by unauthenticated users. The global setting won't override the user specific setting but just determine the styling for unauthenticated pages and maybe as the default for new users. So a user can decide if they want a light or a dark theme independent of the global setting as long as they are logged in.

When this is implemented I think the best default going forward is to have the theme disable and then allow user to enable it if they so choose, inline with the official dark theme. To make it a more smooth transition, I'm thinking of setting the default to enabled for anyone who is currently using the theme. So basically an opt-out for current users and opt-in for new users.

**Comment by mwalbeck** [comment]
18.0.15-beta1 has been released on the app store with the feature fully implemented. There is a global default setting under theming and a user specific setting under accessibility. Any testing would be greatly appreciated.

**Comment by krejcar25** [comment]
Hello, 

I have just tried to install the beta from appstore (I may have done it in a weird way: disabled 18.0.13, removed `breezedark` from `/apps`, unpacked 18.0.15-beta1 and enabled it) and it seems there are some issues with it. The checkboxes in Global settings/Theming and in Personal settings/Accessibility appear, but no way to save them. When I check either of them nothing happens and on refresh they both pop back to disabled state.

Is there any way I can provide more information? Logs or anything? Maybe poke them manually in the database? I just don't know as much about NextCloud as I would like.

Michal

**Comment by mwalbeck** [comment]
Hi,

Thanks for trying it out. There is nothing wrong with the way you installed the beta release, the only thing to be aware of, when doing it that way, are file permissions. Technically there isn't supposed to be a way to manually save the setting, as soon as you tick the checkbox the setting is saved. I'm trying to mimic the accessibility app in how the settings are handled, though I'm using a simpler way of applying the styling, which resulted in a reload being necessary after ticking the checkbox.

Do you by chance have your nextcloud instance in a subdirectory? So example.com/nextcloud or something like that?

**Comment by krejcar25** [comment]
Hi

glad to help! All permissions are all fine, the installation was done as the www-data user. No, the cloud is running on its own domain. The reload itself shouldn't be a problem, however the saving doesn't occur. 

While typing this I realised I didn't even bother opening the developer tools. And sure enough, an HTTP 405 returns from `/apps/breezedark/settings`. I can't find any log messages about why it might happen. There is just a line in apache's access.log, but that isn't really useful. NextCloud's log is silent about this and so is apache's error.log.

Hope it helps.

**Comment by mwalbeck** [comment]
Interesting, how have you setup Nextcloud? Docker, manual, snap or ....? I'll try to replicate your setup and see what I can figure out.

It kind of seems like the routes for the app haven't been registered properly.

**Comment by krejcar25** [comment]
It is just a plain LAMP stack on an Ubuntu 18.04 machine. If you want, I could give you access to the setup and you could poke around 😊

**Comment by mwalbeck** [comment]
Okay, thanks.

Thank you for the offer, but I'll try and see if I can't figure it out on a temp setup first.

**Comment by mwalbeck** [comment]
@krejcar25 There was an issue with the URL's used for the post request. It should be all fixed now, you can try it out in 18.0.15-beta2, available under releases here on Github.

**Comment by krejcar25** [comment]
On it right away!

**Comment by krejcar25** [comment]
OK, the saving now works! 🎉 However I believe there is another issue. Both of the checkboxes are sending the same `theme_enabled` field. When I check the global setting checkbox and refresh, the global one remains unchecked but the per-user one is enabled. What is the name of the global POST field? I can try sending the request manually from Postman.

**Comment by mwalbeck** [comment]
Oh, my bad, the field is supposed to be the same, but the url's should be different, which I can see I forgot. You can try beta3 or if you want you can manually edit the OC.generateUrl in breezedark/js/settings-admin.js from

    apps/breezedark/settings

to

    apps/breezedark/settings/admin

Then it should work as intended. Sorry about that.

**Comment by krejcar25** [comment]
That did it! Works for now @mwalbeck. Tell me when you have the final version 15 on appstore, so I can test it. Thank you for now!

**Comment by mwalbeck** [comment]
Great, thanks for the help.

**Comment by mwalbeck** [comment]
18.0.15 has just been released. For anyone who installed 18.0.14 the theme will be enabled by default and for anyone who hasn't, the theme will be off by default.

There is a short usage description available in the README

**Comment by mwalbeck** [comment]
Mhmm, having it be enabled by default seemed to work in testing, but at least not on my personal instance. If it doesn't work for you, then you can just enable it manually.
