### ISSUE TITLE
KeeWeb

### ISSUE THREAD

**Issue by acatanyg** [mwalbeck/nextcloud-breeze-dark#105]
**Which app would you like to have styled**:
https://apps.nextcloud.com/apps/keeweb

**Your setup (please complete the following information):**
 - Nextcloud 18.0.3

**Comment by mwalbeck** [comment]
Hi,

Thanks for taking interest in the theme. Sadly it won't be possible for me to add styling support for Keeweb. The NC Keeweb app is using an iframe to embed the Keeweb web app into Nextcloud. It isn't really possible for styling outside the iframe to affect content inside the iframe. So for any theming to affect keeweb it would have to be implemented in the NC app or in the keeweb web app.
