### ISSUE TITLE
NC18 + FullTextSearch Styling issue

### ISSUE THREAD

**Issue by BetaLeaf** [mwalbeck/nextcloud-breeze-dark#106]
They say a picture is worth a thousand words. So here ya go. As you can see, certain web elements are not being styled and remain the default background color.
![image](https://user-images.githubusercontent.com/7028351/78515957-ca808f00-7785-11ea-8ab3-9926dd241cf9.png)
![image](https://user-images.githubusercontent.com/7028351/78516010-06b3ef80-7786-11ea-9147-c9e4c384bed4.png)

**Comment by mwalbeck** [comment]
Hi,

Thanks for reporting this. I'll have a look and get it fixed.

**Comment by mwalbeck** [comment]
Should be fixed in 18.0.11. I had a few problems with elasticsearch, but I think I managed to get everything fixed. Let me know if you experience any other issues.

Cheers!
