### ISSUE TITLE
ResourceLocator can not find a web root (root: /var/snap/nextcloud/20007/nextcloud/extra-apps/breezedark, file: index.php/css/breezedark/e4f6-98be-server.css?v=0008b43623c11f070e05fc2eff232fe7, webRoot: , throw: true)

### ISSUE THREAD

**Issue by hackerESQ** [mwalbeck/nextcloud-breeze-dark#107]
**Describe the bug**
This error is logged when the theme is enabled.

`ResourceLocator can not find a web root (root: /var/snap/nextcloud/20007/nextcloud/extra-apps/breezedark, file: index.php/css/breezedark/e4f6-98be-server.css?v=0008b43623c11f070e05fc2eff232fe7, webRoot: , throw: true)`

**To Reproduce**
1. enable the theme
2. check nextcloud.log

**Expected behavior**
No error logged.

**Screenshots**
available upon request

**Setup (please complete the following information):**
 - Nextcloud version: 17.0.5
 - Theme version 17.0.5
 - Browser and browser version Microsoft Edge Version 79.0.309.65 (Official build) (64-bit)

**Additional context**
Using the latest stable snap for nextcloud on Ubuntu.

**Comment by mwalbeck** [comment]
Hi,

I've looked a bit into this, and from what I can see it seems to be an upstream issue https://github.com/nextcloud/server/issues/13556. It is of course made much worse using this theme, as the stylesheet is loaded on every page compared to other apps, where it is only when you use them. Looking through the different issues on this, I haven't been able to find a workaround/fix that I can implement on my side.

**Comment by hackerESQ** [comment]
That's frustrating. But thanks for looking in to it. I'll close this issue. 

Any ideas what needs to be fixed in the core server app to eliminate this? Seems like it's not recognizing resources outside of the webroot.
