### ISSUE TITLE
Custom Icons 

### ISSUE THREAD

**Issue by blackcrack** [mwalbeck/nextcloud-breeze-dark#109]
First at all, thank you for the nice theme addon !  
Well done, therewith it is possible to make it as a "download and install"  
well done !  
  
  
**Which app would you like to have styled**:  
The name of the app and a link to the Nextcloud app store  
files-app and all others with icons  
  
**Your setup (please complete the following information):**  
 - Nextcloud version: 17.0.3  
  
could you maybe look/try for supporting icon-themes as svg/svgz ?  
to have the possible for use own icons like my own icontheme on pling.com  
for customizing all icons in NC ..  
https://www.pling.com/p/1002417/
  
so again, thank you for this nice theme .. and example for other themes ..  
  
best regards  
Blacky

**Comment by mwalbeck** [comment]
Hi,

It think I more or less get what you are asking. You would like to be able to customize the icons and have a theme with your icons in the Nextcloud app store?

The second part I'm not sure if I understood completely and is a bit of a guess, so please correct me if I'm wrong. There is no other way of getting in the app store than going through the default procedure found in the app store documentation. You can install apps manually instead, but the app store is definitely easier.

Now about supporting different icon themes, and this answer can technically apply to changes in general. I don't intend to accommodate customisations more than was is more or less already possible. Which is quite a lot as everything is handled by CSS and CSS variables is utilised through out the theme, which makes it very easy to customise.

Now what about, specifically, icons. Most icons in Nextcloud are handled with CSS, and I think the plan is that all icons should be handled with CSS. That means it's very easy to change the icons to whatever you want. So in this theme I have defined all my icons as variables following the same naming scheme as the default ones. So you can either define some new variables with your icons and change the icon styling rules, or you can override my variables. With that in mind, there are 2 ways to kind of go about it:

The first way is to basically fork the theme and create your own version where you can change the icon variables. This can either be done by including the svg files in your version or you can convert the svg files into base64 strings and embed them directly in the CSS files.

The second way is to utilise the [Custom CSS](https://apps.nextcloud.com/apps/theming_customcss) app in Nextcloud, where you can easily apply you own CSS. You can then convert your svg's to base64 and override what you need to apply your custom icon theme.

I hope that made sense. Now this is just a general overview to give you an idea of your options. 

Overall I don't intend to make any configuration options available through the Nextcloud webui to customise the theme, but I try to make it as easy as possible to allow for customisations through CSS.

**Comment by blackcrack** [comment]
> 
> 
> Hi,
> 
> It think I more or less get what you are asking. You would like to be able to customize the icons and have a theme with your icons in the Nextcloud app store?
> 
more or less, i have also made a theme in old way :
http://www.blackysgate.de/files/folder-root/nextcloud/

for the /theme/ folder, and i have allready set it up the themeicons, but it's no more supported ..
check out the theme or look into..

> The second part I'm not sure if I understood completely and is a bit of a guess, so please correct me if I'm wrong. There is no other way of getting in the app store than going through the default procedure found in the app store documentation. You can install apps manually instead, but the app store is definitely easier.
> 

for installing a theme like your's, exactly :)
what's supportet by Nextcloud api (app-installer)

> Now about supporting different icon themes, and this answer can technically apply to changes in general. I don't intend to accommodate customisations more than was is more or less already possible. Which is quite a lot as everything is handled by CSS and CSS variables is utilised through out the theme, which makes it very easy to customise.
> 
what i try in the next time, if i have the time for it ..

> Now what about, specifically, icons. Most icons in Nextcloud are handled with CSS, and I think the plan is that all icons should be handled with CSS. That means it's very easy to change the icons to whatever you want. So in this theme I have defined all my icons as variables following the same naming scheme as the default ones. So you can either define some new variables with your icons and change the icon styling rules, or you can override my variables. With that in mind, there are 2 ways to kind of go about it:
> 
> The first way is to basically fork the theme and create your own version where you can change the icon variables. This can either be done by including the svg files in your version or you can convert the svg files into base64 strings and embed them directly in the CSS files.
> 
> The second way is to utilise the [Custom CSS](https://apps.nextcloud.com/apps/theming_customcss) app in Nextcloud, where you can easily apply you own CSS. You can then convert your svg's to base64 and override what you need to apply your custom icon theme.
> 
what i ave allready done..

i guess i use your theme to have a example/scelett or so.. for a other theme

> I hope that made sense. Now this is just a general overview to give you an idea of your options.
> 
:+1: 

> Overall I don't intend to make any configuration options available through the Nextcloud webui to customise the theme, but I try to make it as easy as possible to allow for customisations through CSS.

no, it's total easy for more experts to use youre "app" or theme and custom it, other name,   
and custom the css-styles, make more sense to have later a package to move it/upload up in the  store as custom theme  ..  
best regards
Blacky

**Comment by mwalbeck** [comment]
You are definitely very welcome to use my theme as the foundation for your own. That's one of the reasons it's here, on github, and licensed under the AGPL.

Let me know if you have any other questions.

Cheers!
