### ISSUE TITLE
Nextcloud Deck due date colour

### ISSUE THREAD

**Issue by Leon0402** [mwalbeck/nextcloud-breeze-dark#112]
The colours for the due date background and icons seem to not work always correctly. The text colour was up to now always right, although I don't have to many cards, to be absolutly sure about that.

Bug 1: Sometimes the icon colour is incorrect (the text colour is in all of my cards correct)
![image](https://user-images.githubusercontent.com/33933142/79211673-d1269a80-7e46-11ea-9108-3369ab05d8ea.png)

Bug 2: Sometimes due dates have no background at all
![image](https://user-images.githubusercontent.com/33933142/79211525-a5a3b000-7e46-11ea-879d-9bf691dca904.png)

**Comment by mwalbeck** [comment]
Thanks for reporting this.

I can see they have a background colour for cards that have a due date within one day, that I don't have in this theme. I'll get that fixed along with the dark calendar icon.

So the background colour for due dates are the following:

Past due date: red
Within 8 hours: orange
Within 1 day: yellow
2 days+: nothing

**Comment by Leon0402** [comment]
I see, that sounds about right. Although the picture I posted with the wrong icon colour actually had a background in the default theme. Unfortunatly I was not able to reproduce that behaviour. 

On the other hand I managed to get one within 1 day (at least that's what the card says) without a background
![image](https://user-images.githubusercontent.com/33933142/79253355-59c32c00-7e83-11ea-8a59-480a1b354265.png)

It seems to me that the colour is based on the actual time (probably like you said), while the information in the label is rounded up or down. That can be a little bit confusing in my opinion as I then have cards, which show all "1 Day", but only some of them have a background. 
So maybe I should open up an issue to make the background color based on the information in the label instead of the actual time.

**Comment by mwalbeck** [comment]
In my testing the background colour change was bugged and needed a refresh for it to change.

You could, but considering the issue, I would hold off because of the upcoming Deck 1.0 release. It contains a complete rewrite of the interface, and I assume it will be out together with NC19, but will also support NC18.

**Comment by mwalbeck** [comment]
Fixed in 18.0.12
