### ISSUE TITLE
Calendar: Repeat day highlighting broken

### ISSUE THREAD

**Issue by TheAsuro** [mwalbeck/nextcloud-breeze-dark#117]
**Describe the bug**
The selection of "repeat days" in the calendar is not displayed correctly and only highlights the last clicked button instead of all selected days. This is broken for the repeat modes of Week, Month and Year.

**To Reproduce**
1. Go to the calendar
2. Create a new entry
3. Go to the "Repeat" tab
4. Select Week/Month/Year
5. Click on multiple days
6. Compare the highlighted days to the actual list of selected days below

**Expected behavior**
The actual selected days are highlighted, instead of only the last clicked one. (Same behaviour as default theme)

**Screenshots**
https://i.imgur.com/b2Lrz8q.png
(Wednesday and Thursday are selected, but Tuesday is highlited)

**Setup**
 - Nextcloud version: 18.0.3
 - Theme version: 18.0.12
 - Nextcloud calendar version: 2.0.3
 - Browser and browser version: Firefox 75.0

**Comment by mwalbeck** [comment]
Hi,

Thanks for reporting this. I'll have a look and get it fixed.

**Comment by mwalbeck** [comment]
Thanks again for reporting this.

I've have pushed a fix to master. It will be in 18.0.13, which will hopefully be released during the weekend.

Forgot to tag the issue in the commit message, so for reference: https://github.com/mwalbeck/nextcloud-breeze-dark/commit/a2045ade60b5f8382135b3152bdb58fc5a8dc672
