### ISSUE TITLE
Breeze dark for Flowupload/ocDownloader/Scanner/epubreader/Weather/ocSMS apps?

### ISSUE THREAD

**Issue by e-alfred** [mwalbeck/nextcloud-breeze-dark#119]
Hello, I maintain a few apps and users ask if the Breeze Dark theme works with those apps. Sadly I didn't test them, maybe you could help me with the theming?

**Which app would you like to have styled**: 
Flowupload https://github.com/e-alfred/flowupload
ocDownloader https://github.com/e-alfred/ocdownloader
Scanner https://github.com/e-alfred/nextcloud-scanner
Epubreader https://github.com/e-alfred/epubreader
ocSMS https://github.com/nextcloud/ocsms
Weather https://github.com/nextcloud/weather

**Your setup (please complete the following information):** Nextcloud 18.0.3 / 19 Beta 4

**Comment by e-alfred** [comment]
I tested the app listed above and it seems all work except ocDownloader.

**Comment by mwalbeck** [comment]
Hi, 

Thanks for getting in touch, great to hear it more or less works. Currently I support flowupload, weather and ocsms, but ocsms could use a touch up. Yes, scanner and epubreader seems to work as is and I doubt epubreader would lend itself well to theming, other than what is provided in the app itself.

I'll have a good look at ocDownloader and add it to the list of supported apps.

**Comment by e-alfred** [comment]
Epubreader doesn't need theming as it opens the file in a new tab/window anyway (and it has dark mode already) so it shouldn't be a problem. The Scanner app is just one modal window for selecting a few options and shouldn't be much of a problem.

If you could add ocDownloader, that would be awesome!

**Comment by mwalbeck** [comment]
Styling has been added in 18.0.14, which has just been released
