### ISSUE TITLE
Compatibility with 19

### ISSUE THREAD

**Issue by sunjam** [mwalbeck/nextcloud-breeze-dark#120]
Not yet supported on 19.0.0 beta5. :heart:

**Comment by mwalbeck** [comment]
Thanks for the help with nc19 testing, I greatly appreciate it. I've been meaning to release a nightly build for NC19 to make it a bit easier to test, I'll get around to doing that during the weekend.

**Comment by mwalbeck** [comment]
Initial NC19 release is out.
