### ISSUE TITLE
Add to Accessibility selection menu

### ISSUE THREAD

**Issue by sunjam** [mwalbeck/nextcloud-breeze-dark#121]
I'd like to be able to select Breeze Dark & the included Dark Mode from the Accessibility Menu after installation.  Thanks for considering!  Test on v19.0.0 beta5

![Screenshot_20200430_152139](https://user-images.githubusercontent.com/1787238/80764808-51f7be80-8af6-11ea-9c5f-a5d8695a3b56.png)

**Comment by e-alfred** [comment]
This would be very helpful so each user can select their preferred theme (light, dark, breeze, dyslexia) instead of having to activate/deactivate the app and users only having one option.

**Comment by mwalbeck** [comment]
You're in luck, I'm currently working on it. It's mostly done just need to work out a few kinks.

Related issue #104
