### ISSUE TITLE
App icons under (...) menu are black

### ISSUE THREAD

**Issue by sunjam** [mwalbeck/nextcloud-breeze-dark#122]
App icons under (...) on top bar appear as black on 19.0.0 beta5

![Screenshot_20200430_152346](https://user-images.githubusercontent.com/1787238/80765021-d9453200-8af6-11ea-8c85-11f5a731cdf1.png)

**Comment by mwalbeck** [comment]
This seems to be fixed in 19-rc1, so I'll go ahead and close this issue.
