### ISSUE TITLE
Unable to set Global or Personal theme settings

### ISSUE THREAD

**Issue by republicus** [mwalbeck/nextcloud-breeze-dark#127]
**Describe the bug**
App **Usage** suggests it's possible to set Global and Personal settings for Breeze-Dark theme; but options do not exist.

**To Reproduce**
Admin settings > Theming > Breeze Dark
[or]
Personal settings > Accessibility > Breeze Dark

**Expected behavior**
Set Global or Personal theme settings.

**Setup:**
 - Nextcloud version: 17.0.2
 - Theme version 17.0.11

**Additional context**
I love this theme. But, not everyone prefers a dark theme. I had temporarily disabled the app/theme because it appears to be not possible to disable the theme for users who like a light theme.
Then I re-read the Usage subsection of the Readme and was happy to give it a try... But, none of the options outlined exist. There is no Global or Personal options for Breeze Dark - unless its disabled, it's always on.

**Comment by mwalbeck** [comment]
Hi,

This is currently only available in the newly released 18.0.15. Currently I don't have any plans to backport it to nc17, but it should be fairly simple. If I find the time or someone else wants to do it, I'll be happy to merge it. For now I'll be focusing my time on fixing the current issues with nc18 and getting ready for the upcoming nc19 release.

**Comment by republicus** [comment]
Great, thanks! I do intend on upgrading soon now that all my apps appear to be recently updated to support NC 18.

Is it possible to style per domain as a config setting?
I'm using several domain proxies and am styling each in *config/domains.config.php*

eg:

`$CONFIG['theme']='breeze-dark';`

This currently only stylizes the login page when i copy the app contents to the theme folder.

**Comment by mwalbeck** [comment]
Currently no, this theme used to use the theming folder, and you can find an older version of the theme for nc17 in the 17 branch, which uses the theming folder. The theming is handled a bit differently which makes it so they are only somewhat compatible. Though, the biggest reason for your issue above is that the app supports sass directly and the theming folder doesn't, so it has to be compiled to css first.

For it to be possible with the app one would probably have to add logic for it to the app itself.
