### ISSUE TITLE
Fix TOTP challenge button

### ISSUE THREAD

**Issue by abyssox** [mwalbeck/nextcloud-breeze-dark#131]
**Describe the bug**
TOTP challenge button after login is not dark styled

**To Reproduce**
1. Have Addin "Two-Factor TOTP Provider" activated
2. Login
3. On TOTP challenge site the button is not dark styled

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/4539953/82027537-aec9ac00-9694-11ea-8689-9b75211de225.png)

**Setup (please complete the following information):**
 - Nextcloud version: 18.0.4
 - Theme version: 18.0.15
 - Browser and browser version: Firefox 68.8 ESR

**Comment by mwalbeck** [comment]
Hi,

I looked a bit into this and it seems the guest.css stylesheet isn't being loaded. Can you check your browser console for any errors? Or maybe you have a browser addon blocking it? You can also try to reinstall the theme or run the occ maintenance:repair command.

**Comment by abyssox** [comment]
Hi,

unfortunately:

- no errors in browser console
- no browser addon active
- occ maintenance:repair executed, but button still not dark

I checked with multiple browsers (latest Chromium Edge and Firefox).

**Comment by mwalbeck** [comment]
Thanks for getting back to me. 

Mhmmm, are you using the theming app or custom css app to make any style changes, if so could you share them.

Also just to make sure as I didn't specify it, did you have a look at the network tab in the firefox developer tools? If not try and see if you can find the guest.css file and see which HTTP code it got. When you find it you can hover over the filename to get the full path, to make sure it's the correct one, or more specifically that it comes from breezedark and not core.

**Comment by abyssox** [comment]
Fixed it!

Forgot to enable checkbox "Enable Breeze Dark theme by default" in theming app.
Thanks for the hint with the theming app ;)
