### ISSUE TITLE
Auto-Changing between light and dark theme depending on system time / system

### ISSUE THREAD

**Issue by guyfromouttaspace** [mwalbeck/nextcloud-breeze-dark#135]
Maybe a nice feature: Set some auto change from light to dark and vice versa, depending on time / location or system setting.

**Comment by guyfromouttaspace** [comment]
Maybe like: [Feature] Night mode / day mode #98

**Comment by guyfromouttaspace** [comment]
-- could be (maybe) implemented via triggering a switch to activate / deactivate the app? So day mode is just the default mode depending on time or settings

**Comment by mwalbeck** [comment]
Hi, thanks for showing interest in the theme.

> Maybe like: [Feature] Night mode / day mode #98

Yes, I would consider them the same feature request.

> -- could be (maybe) implemented via triggering a switch to activate / deactivate the app? So day mode is just the default mode depending on time or settings

This pull request #115 laid the ground work for something like this to work properly. So right now it's possible for people to enable and disable the theme without affecting others. So the missing component is the logic to automatically enable and disable the theme depending on that user's settings.

I'm going to close this in favour of the other issue, but do go and give it a thumbs up, It's an easy way for me to know how many people would like to see a certain feature.
