### ISSUE TITLE
App Order: app icons display in black instead of white with Breeze Dark app enabled

### ISSUE THREAD

**Issue by DalekDave** [mwalbeck/nextcloud-breeze-dark#136]
**Which app would you like to have styled**:
https://apps.nextcloud.com/apps/apporder

**Your setup (please complete the following information):**
 - Nextcloud version: 18.0.4
I am running my Nextcloud instance with the Theming app and the Custom CSS app enabled

**Comment by mwalbeck** [comment]
Thanks for taking an interest in the theme. Support for App Order will be in 18.0.17.

**Comment by DalekDave** [comment]
@mwalbeck thank you for your work on this. I got the app update last night. Now App Order is displaying perfectly. :-)
