### ISSUE TITLE
Icon color integration for Collabora Online (/apps/richdocuments)

### ISSUE THREAD

**Issue by DalekDave** [mwalbeck/nextcloud-breeze-dark#138]
**Which app would you like to have styled**:
https://apps.nextcloud.com/apps/richdocuments

**Your setup (please complete the following information):**
 - Nextcloud version: 18.0.4 with Nextcloud's Collabora Online app enabled, and with Collabora Online installed and working on the same Linux server

Right now, the Collabora Online icons in the personal settings and in the NC administration settings are displaying in black. Would you have time to add this app to your Breeze Dark app?

If you need an account on my Nextcloud instance to see the Collabora Online app up and running, please let me know and I can give you one.

Thanks again for your work on the Breeze Dark app.... It's all displaying beautifully at https://collaboration.cafe :-)

**Comment by mwalbeck** [comment]
Could you provide a screenshot? It might be because I don't use any templates for collabora, but I don't see any black icons in either settings view.

**Comment by DalekDave** [comment]
Sorry, Magnus, I just checked again... You're right... I think I got a multi-tasking error... I'll close this.
