### ISSUE TITLE
Breeze Dark styling for Ebook reader app when reading books

### ISSUE THREAD

**Issue by DalekDave** [mwalbeck/nextcloud-breeze-dark#140]
**Which app would you like to have styled**:
Ebook reader https://apps.nextcloud.com/apps/files_ebookreader

**Your setup (please complete the following information):**
 - Nextcloud version: 18.0.4

Ebook reader only offers a black-text-on-white-page mode. Personally, I prefer a dark page with white text, with which there is less glare.

I'd love to see this Ebook reader app working optimally, because the ability to read epub files is a big plus and a big pleasure in Nextcloud.

I guess that's maybe more a question of upgrading the Ebook reader app with a day/night mode toggle... But could it also be done through the Breeze Dark app, by simply theming the app in Breeze Dark colors?

I realize that the 3 styling requests I filed constitute a lot more work than a simple app like App Order... I'd be happy to provide any kind of practical help you might like.

Off-topic: would you have any links to where I might learn about app development for Nextcloud? I'd like to lean about it so I could maybe take over an orphaned project, or one that needs more active development, like Ebook reader, for example...

**Comment by mwalbeck** [comment]
First off, the latest release of this app is for NC16 so I'm not willing to add support for it in the theme unless somebody updates it and maintains it.

For app development the best place and I also think only place is really the Nextcloud developer docs, https://docs.nextcloud.com/server/latest/developer_manual/

There is also a section on the Nextcloud forum for development where you can direct any questions you might have when it comes to developing for Nextcloud in general.

**Comment by DalekDave** [comment]
Yes, I can understand, it's not a very active project. The dev's last commit was more than 11 months ago.  But it still works in NC and, to the best of my knowledge, it's the only e-book reader currently available for NC...

(Thanks for the NC dev tips. :-) )

**Comment by mwalbeck** [comment]
Have you had a look at this one https://apps.nextcloud.com/apps/epubreader

**Comment by DalekDave** [comment]
Oh! Cool! Thank you! Just what I was looking for: has a dark mode, it's recently updated, it's configurable. Thanks, Magnus! :-)
