### ISSUE TITLE
Respect background-image in navigation

### ISSUE THREAD

**Issue by republicus** [mwalbeck/nextcloud-breeze-dark#143]
I like the gradient in Nextcloud 18 navigation... I just don't like the gradient to blue. So I started messing around with custom themes and adjusted the gradient colors.. 
Only, Breeze-Dark ignores it.

When Breeze-dark is not enabled, Nextcloud defaults to a gradient header background-image.
When Breeze-dark is enabled, it defaults to the theme's color-primary (in themes' defaults.php) -- _unless, background-image is used._ 

If background-image is used: Dark-Breeze ignores **both** color-primary and background-image; meaning that Breeze-dark defaults to black header background-color. 

In order to use gradient (background-image) when Breeze-Dark **is not** enabled **and**  background-color when Breeze-Dark **is** enabled, I must separately define both. 

Please allow Breeze dark to use custom themes' style for header/navigation using background-image. 

**Which app would you like to have styled**:
Nextcloud wide

**Your setup (please complete the following information):**
 - Nextcloud version: 18.0.4

### Defaults

- example custom theme with no changes

![image](https://user-images.githubusercontent.com/47370709/82958387-48da0000-9f83-11ea-8b87-4dab57156fed.png)

- customization of example theme

`#body-public #header {
        background-image: linear-gradient(40deg, #3a9240 10%, #003300 100%);
}`

![image](https://user-images.githubusercontent.com/47370709/82957034-21cdff00-9f80-11ea-94c1-604e38fa64a8.png)

### Breeze-Dark enabled

- example custom theme with no changes (uses _color-primary_ from defaults.php)

![image](https://user-images.githubusercontent.com/47370709/82958675-e3d2da00-9f83-11ea-97cf-bc17fb68f270.png)

- customization of example theme

`#body-public #header {
        background-image: linear-gradient(40deg, #3a9240 10%, #003300 100%);
}`

![image](https://user-images.githubusercontent.com/47370709/82958082-95710b80-9f82-11ea-8748-b1aa2265188a.png)

- customization of example theme

```
#body-public #header {
        background-image: linear-gradient(40deg, #3a9240 10%, #003300 100%);
        background-color: #3a9240;
```

![image](https://user-images.githubusercontent.com/47370709/82957101-44f8ae80-9f80-11ea-9d3c-8d8f0f370403.png)

**Comment by mwalbeck** [comment]
I always try to be compatible with the theming app where you can change the header colour, and with it the gradient, but it wasn't possible this time because of how they implemented it.

Now I have a small recommendation, if you just want to change the header gradient, I can recommend you use the Custom CSS app instead of doing a custom theme, it's much simpler. Now to the actual problem at hand.

Remember to have all 3 id's for the header style, you might already be aware of that, I wasn't want to be sure.
```
#body-user #header,
#body-settings #header,
#body-public #header
```

And then you just need to slap an !important on the end of the background-image rule so you get something like this:
```
#body-user #header,
#body-settings #header,
#body-public #header { 
    background-image: linear-gradient(40deg, #3a9240 10%, #003300 100%) !important;
}
```
Then it works as intended.

**Comment by republicus** [comment]
Yes, indeed it does :)
Thanks for taking the time to share that.
