### ISSUE TITLE
Deck: Text colour while editing description is black

### ISSUE THREAD

**Issue by tigexplorer** [mwalbeck/nextcloud-breeze-dark#144]
**Which app would you like to have styled**:
Deck
https://apps.nextcloud.com/apps/deck

**Your setup (please complete the following information):**
 - Nextcloud version: [e.g. 18.0.3]

In the details view of a card, the description section has black text on grey background.

![Deck_Card_Description](https://user-images.githubusercontent.com/43775552/82995275-b2015800-a003-11ea-91b1-17084fff5881.png)

**Comment by mwalbeck** [comment]
Thanks for reporting this, fix will be in 18.0.18 / 19.0.1
