### ISSUE TITLE
Theme in shared folders accessed by anonymous

### ISSUE THREAD

**Issue by krejcar25** [mwalbeck/nextcloud-breeze-dark#145]
**Describe the bug**
When a shared folder is accessed by anonymous user via a share link, the theme depends on the setting of the owner of the folder, not on the global setting.

User | Global | Result
-----|--------|------
L | L | L
L | D | L
D | L | D
D | D | D

**To Reproduce**
1. Create a share link to a folder and open it in anonymous/other browser
1. Enable/Disable global setting and see it has no effect on the shared folder
1. Enable/Disable user setting and see that it does

**Expected behavior**
Global setting should determine how an anonymous user sees shared folders

**Setup (please complete the following information):**
 - Nextcloud version: 18.0.4
 - Theme version 18.0.16
 - Browser and browser version:
   `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0 Safari/605.1.15`

**Comment by mwalbeck** [comment]
Issue cleanup.

You're welcome to reopen this issue if there are any updates.
