### ISSUE TITLE
Background reset when I enable this theme

### ISSUE THREAD

**Issue by antoniogamiz** [mwalbeck/nextcloud-breeze-dark#146]
Hi, 
I have enabled this theme in nextcloud instance and I'm quite pleased with the result. Nonetheless, I have noticeed that my background image has been overriden by this action. Is there anyway I can both my old background and this theme?
Thanks.

**Comment by mwalbeck** [comment]
Can you be a bit more specific about your issue. I would generally recommend to handle something like this as a possible bug and fill out the information on the bug report template. It makes it easier for me to help you. Now for a few questions:

What is your nextcloud version?
What is the version of the Breeze Dark theme?
Are we talking about a background image on the login screen, or somewhere else? 
How did you initially add the background image to your nextcloud instance?

**Comment by severus-tux** [comment]
> Hi,
> I have enabled this theme in nextcloud instance and I'm quite pleased with the result. Nonetheless, I have noticeed that my background image has been overriden by this action. Is there anyway I can both my old background and this theme?
> Thanks.

Is it this?  https://github.com/mwalbeck/nextcloud-breeze-dark/issues/159#issue-675704880

**Comment by mwalbeck** [comment]
It's most likely the same problem as noted above so I'm going to close this issue.

If it's not the same issue then you're welcome to reopen this issue.
