### ISSUE TITLE
Black folders

### ISSUE THREAD

**Issue by dducted** [mwalbeck/nextcloud-breeze-dark#147]
Hi there,

First of all, thanks for the great theme!

I just have a little issue that the folders are in full black, see screenshot below:

[https://i.imgur.com/xdQAWr7.png](img)

Any idea how to solve this?

**Comment by mwalbeck** [comment]
Have you changed the colour setting using the theming app? That is at least my first thought, as that setting also applies to folders.

**Comment by dducted** [comment]
That was it, thanks for your help. Much appreciated!
