### ISSUE TITLE
Latest update breaks login from mobile browser

### ISSUE THREAD

**Issue by ndnihil** [mwalbeck/nextcloud-breeze-dark#148]
**Describe the bug**
Latest BreezeDark theme update breaks login from mobile browser. Fails login and redirects back to login page. Desktop (FF/Linux) not impacted. Reverting to stock Nextcloud theme returns expected behavior.

**To Reproduce**
- Navigate to NC login page
- Attempt to log in

**Expected behavior**
- Expected to log into NC instance

**Screenshots**
- Not particularly useful but can take some if desired. Standard Nextcloud login form redirecting back to standard Nextcloud login form. 

**Setup (please complete the following information):**
- Nextcloud  18.0.4
- BreezeDark 18.0.18
- Android 10
- Firefox 68.8.1

**Additional context**
Server logs throwing 499/404 when BD theme in play, not present when stock theme used:

"GET /login HTTP/2.0" 200 4162 "-" "Mozilla/5.0 (Android 10; Mobile; rv:68.0) Gecko/68.0 Firefox/68.0"

"GET /apps/theming/image/logo?v=23 HTTP/2.0" 499 0 "-" "Mozilla/5.0 (Android 10; Mobile; rv:68.0) Gecko/68.0 Firefox/68.0"

"GET /apps/theming/icon?v=23 HTTP/2.0" 499 0 "-" "Mozilla/5.0 (Android 10; Mobile; rv:68.0) Gecko/68.0 Firefox/68.0"

"GET /apps/theming/image/background HTTP/2.0" 404 1 "-" "Mozilla/5.0 (Android 10; Mobile; rv:68.0) Gecko/68.0 Firefox/68.0"

**Comment by mwalbeck** [comment]
I've tried to reproduce your issue, but I haven't been able to on my end. Can you try and log in using a private window? or another browser on your phone?

**Comment by ndnihil** [comment]
Now I'm unable to reproduce it as well... I toggled from stock theme back to BD with an active/logged in session on the phone browser and now it will let me log out/in without issue, even in private tab. Perhaps the act of disabling and re-enabling the theme resolved it?

Apologies for the alarm.

**Comment by mwalbeck** [comment]
No worries, it was most likely some sort of caching issue, and disabling and re-enabling the theme triggered a refresh of said cache.
