### ISSUE TITLE
Nextcloud News Support

### ISSUE THREAD

**Issue by F3000** [mwalbeck/nextcloud-breeze-dark#149]
Would be cool when the dark theme can cover this :) 

**Which app would you like to have styled**:
The name of the app and a link to the Nextcloud app store

Nextcloud News  

https://apps.nextcloud.com/apps/news

**Your setup (please complete the following information):**
 - Nextcloud version: 18.0.4

**Comment by mwalbeck** [comment]
It's already supported, you can have a look at which apps are currently supported here https://github.com/mwalbeck/nextcloud-breeze-dark/wiki/Styled-apps
