### ISSUE TITLE
Styling for FullTextSearch

### ISSUE THREAD

**Issue by mwalbeck** [mwalbeck/nextcloud-breeze-dark#15]
new issue for request made in #2 

The newest is working very well on NC 13, thank you very much for continuing your work on this theme.

I'd like to see the FullTextSearch (Nextant replacement) app in the list. Right now, they use a custom Search icon to the left of the Contacts search icon, and with the theme in place, it's not available (e.g., if you use FullTextSearch and this theme, you can't search).

Thanks!

**Comment by mwalbeck** [comment]
@adx442 I've looked into it and it seems to be an issue with FullTextSearch. When you are using a custom theme with FullTextSearch it removes the default search icon, as it should, but then doesn't load their own replacement. The same happens if you deactivate the theming app but keep the default Nextcloud theme. I haven't looked more into the reason why, but it's not something I can fix on my end.

**Comment by mwalbeck** [comment]
I created an issue about it on the FullTextSearch github page and a fix have been made, should be included in the next release. I'll look into styling the rest.

**Comment by adx442** [comment]
Thanks very much, it's working now with their new commit.  Much appreciated for the assist!
