### ISSUE TITLE
PhoneTrack app styling request

### ISSUE THREAD

**Issue by jpereztenerife** [mwalbeck/nextcloud-breeze-dark#152]
**Which app would you like to have styled**:
PhoneTrack: [https://apps.nextcloud.com/apps/phonetrack](https://apps.nextcloud.com/apps/phonetrack)

**Your setup (please complete the following information):**
 - Nextcloud version: 19.0.0
 - PhoneTrack version: 0.6.3 (latest available). Configured and working.

The sidebar in the PhoneTrack application shows white text over white background and can't be used properly.

Thank you so much for such a wonderful work with Breeze Dark!

**Comment by mwalbeck** [comment]
I can see the author of PhoneTrack add support for dark themes before I got around to styling it so I have made a few adjustments so it fits a bit better with the rest of the theme. Will be included in 21.0.2 and 20.0.7.
