### ISSUE TITLE
Style Suspicious Login

### ISSUE THREAD

**Issue by SuperSandro2000** [mwalbeck/nextcloud-breeze-dark#153]
**Which app would you like to have styled**:
Suspicious Login https://apps.nextcloud.com/apps/suspicious_login

**Your setup (please complete the following information):**
 - Nextcloud version: 18.0.5

The graph under admin settings, security is barely readable.

**Comment by mwalbeck** [comment]
Yeah, It's not great. I'll change the background colour to white so it's readable. There isn't much else I can do.

**Comment by mwalbeck** [comment]
The issue is it's shown as a canvas, which is more or less like an iframe, which means I can't style the contents, only the background. So the background will be changed in the next release, 19.0.2 / 18.0.20

**Comment by SuperSandro2000** [comment]
Looks way better now. Thanks!
