### ISSUE TITLE
Text colour when copying conflicts is black

### ISSUE THREAD

**Issue by prezeskk** [mwalbeck/nextcloud-breeze-dark#154]
**Describe the bug**
Text colour when copying conflicts is black on grey background.

**To Reproduce**
1. Go to files
2. Click on add file
3. Scroll down to attach existing file

**Screenshots**
![Zrzut ekranu 2020-06-01 10 11 39](https://user-images.githubusercontent.com/1465859/84600532-1f254200-ae7a-11ea-90d4-b1b5919e8582.png)

**Setup (please complete the following information):**
 - Nextcloud version: 18.0.6
 - Theme version: 18.0.18
 - Browser: Firefox 77.0.1 x64, Chrome  83.0.4103.97 x64

**Comment by mwalbeck** [comment]
Thanks for reporting this, it'll be fixed in 19.0.2 / 18.0.20
