### ISSUE TITLE
[Feature Request] Selective Theming

### ISSUE THREAD

**Issue by TheColin21** [mwalbeck/nextcloud-breeze-dark#155]
It would be great to be able to choose which parts of Nextcloud will be themed. I would like the login screen to stay the way I configured it in the first place while getting Breeze Dark as standard theme in Nextcloud.

**Comment by mwalbeck** [comment]
I don't see any problems with this. The login screen and any public pages are currently a separate stylesheet from the rest of the theme. So adding this option wouldn't be too much trouble and I can see good reasons for wanting it. Are you just interested in specifically the login screen and still having the public pages styled?

**Comment by TheColin21** [comment]
At the moment I'm only interested in the login screen but I'll take what I can get. If it's easy that's even better

**Comment by rosareven** [comment]
I'd like colours like the menu selection and links to be my theme's colour instead of the blue that came with BreezeDark. For example here's a screenshot from my Notes app. 
![image](https://user-images.githubusercontent.com/17244066/90747496-e5811500-e2c8-11ea-8c27-510749282343.png)

**Comment by mwalbeck** [comment]
I finally got around to implementing this and it will be in the next release.

@rosareven I don't plan to implement settings to allow for that type of customisability. Though, I define all the colours used as CSS variables so with the Custom CSS app you can modify the themes colours that way. If you have any questions about it you're welcome to open up a new issue.
