### ISSUE TITLE
Errors when using breezedark on snap version of nextcloud

### ISSUE THREAD

**Issue by yurividal** [mwalbeck/nextcloud-breeze-dark#156]
Just installed nextcloud from snap, and after enabling breezedark, mynextcloud becomes super unstable and slow.
My log is completely flooded with breezedark errors, such as: 

> {"reqId":"DSFEAbWQAMPVaiwyuklv","level":3,"time":"2020-07-20T20:06:34+00:00","remoteAddr":"XX.XX.XX.XX","user":"XXX@XXX.com","app":"lib","method":"GET","url":"/index.php/settings/user","message":"ResourceLocator can not find a web root (root: /var/snap/nextcloud/21796/nextcloud/extra-apps/breezedark, file: index.php/css/breezedark/68c8-be55-server.css?v=42d3b95ac32a0c0d54442382e7dbae40, webRoot: , throw: true)","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:78.0) Gecko/20100101 Firefox/78.0","version":"19.0.0.12"}

**Comment by mwalbeck** [comment]
This is an upstream issue, so there is sadly not much I can do about it. There is a bit more info over here #107

**Comment by Fuseteam** [comment]
this doesn't seem to be an issue anymore?

**Comment by yurividal** [comment]
I cant confirm. I have uninstalled breezark

**Comment by mwalbeck** [comment]
I've had a look through the different issues and yes, it seems that a fix has been made and is available in all currently supported versions of Nextcloud.
