### ISSUE TITLE
Notes app: rename buttons glitched

### ISSUE THREAD

**Issue by SuperSandro2000** [mwalbeck/nextcloud-breeze-dark#157]
**Describe the bug**
When I want to rename a note in the Notes app this happens:

![image](https://user-images.githubusercontent.com/7258858/88802771-d5838300-d1ab-11ea-9468-9029d1224106.png)

**To Reproduce**
1. Open Notes App
2. Rename a Note

**Expected behavior**
The arrow and cross should only appear once like they do without the theme.

**Screenshots**
![image](https://user-images.githubusercontent.com/7258858/88802771-d5838300-d1ab-11ea-9468-9029d1224106.png)

**Setup (please complete the following information):**
 - Nextcloud version: 18.0.7
 - Theme version 18.0.21
 - Browser and browser version: Chrome 84

**Additional context**

**Comment by mwalbeck** [comment]
Thanks for reporting, fixed in 18.0.22 and 19.0.4
