### ISSUE TITLE
Invalid code signature

### ISSUE THREAD

**Issue by Dkapps** [mwalbeck/nextcloud-breeze-dark#158]
**Describe the bug**
Hi, 
I just installed a fresh nextcloud instance and when I tried to install this app, I was hit with the following error : `App with id breezedark has invalid signature`

**To Reproduce**
1. Go to Apps
2. Select the `Breeze Dark` app
2. Click on `Download and enable`

**Expected behavior**
The app install without a hitch

**Screenshots**
![image](https://user-images.githubusercontent.com/9819361/89718794-41db5f00-d9c2-11ea-8b8d-41ee0e4bf1ed.png)

**Setup (please complete the following information):**
 - Nextcloud version: [e.g. 19.0.1]
 - Theme version [e.g. 1.10.0
 - Browser and browser version [e.g. Firefox 79.0]

**Additional context**
I am using a docker version of Nextcloud not publicly exposed to the internet (for now)

**Comment by mwalbeck** [comment]
By accident I uploaded the wrong archive when uploading the latest release, so the signature for 19.0.3 got a bit messed up. 19.0.4 should be available for you shortly, which shouldn't have any signature issues.

**Comment by Dkapps** [comment]
@mwalbeck Well, that's good news ! I can't wait for 19.0.4 to be available because the default white theme hurts my eyes 😅 🕶️

**Comment by mwalbeck** [comment]
Let me know if it still isn't working

**Comment by Dkapps** [comment]
@mwalbeck 19.0.4 installed without a hitch ! I'm closing the issue then
