### ISSUE TITLE
Latest version overrides login background image

### ISSUE THREAD

**Issue by severus-tux** [mwalbeck/nextcloud-breeze-dark#159]
After updating to the latest version, the theme overrides the login image and sets a default nextcloud dark background image.

**To Reproduce**
1. Enable breeze-dark theme.
2. Go to `Settings` > `Administration` > `Theming`
3. Upload and set a new "Login image"

**Expected behavior**
The login screen should have the selected background image. Like this (disabled breeze-dark)
![1](https://user-images.githubusercontent.com/21301040/89733846-e79bd600-da75-11ea-9a60-62c611531b7d.png)

**Current behaviour**
The theme is overriding the login image.
![2](https://user-images.githubusercontent.com/21301040/89733877-1b76fb80-da76-11ea-9501-cdf827d63906.png)

**Setup :**
 - Nextcloud version: 19.0.1
 - Theme version  19.0.4
 - Browser and browser version : Mozilla Firefox 79.0, Chromium 84.0.4147.89

**Additional context**
It was working fine in previous versions of the theme.

**Comment by mwalbeck** [comment]
I'm not able to replicate the issue on my end. I also didn't change any styling related to the login page, so it's weird it has stopped working now.

It's behaving like it isn't able to load your custom background when the theme is enabled. Can you open up the developer tools of your browser and share what styling is being applied to the body element?

**Comment by severus-tux** [comment]
> It's behaving like it isn't able to load your custom background when the theme is enabled. Can you open up the developer tools of your browser and share what styling is being applied to the body element?

(Sorry for pasting screenshots instead of code. I wanted to show the strike through on the image line)

![Screenshot from 2020-08-09 21-34-21](https://user-images.githubusercontent.com/21301040/89736654-921cf480-da88-11ea-912a-e6a062005901.png)
![Screenshot from 2020-08-09 21-34-40](https://user-images.githubusercontent.com/21301040/89736657-947f4e80-da88-11ea-862e-101efbf294f2.png)

`'/index.php/apps/theming/image/background?v=20'` is what we want it to load.

**Comment by mwalbeck** [comment]
Perfect. The only thing I see that is different from my setup is the fact that I have a rewrite rule to remove index.php and you don't, so that might be it. 

I'm overwriting the background-image rule with my own, so it's mostly likely the location I'm looking that doesn't quite work with your setup. I'll have a closer look and see what I can do.

**Comment by severus-tux** [comment]
>  I also didn't change any styling related to the login page

I think I skipped the previous version. I am not sure if it is a new bug in version 19.0.4. It could be possible that the bug popped up in version 19.0.3. But  am sure it was working fine in version 19.0.2. 

Sorry if I mislead you with my title.

**Comment by mwalbeck** [comment]
No worries, It's a change I made back in February, so it's weird you haven't had this issue before now.

Anyway, it isn't something I can do much about currently, if I also want to have the default login screen background style as it is now. I'm planing some bigger changes including improving compatibility with the theming app, so it's something I'm going to return to.

In the meantime the best I can do is give 2 workarounds.

1. I'm assuming you're using apache here, so please correct me if I'm wrong. You can follow the steps from the documentation and switch to using "pretty urls", aka urls without index.php in them, https://docs.nextcloud.com/server/19/admin_manual/installation/source_installation.html#pretty-urls

2. You can install the custom css app from the nextcloud app store and add the following css rule.
```
body#body-login {
	background-image: url('../../../index.php/apps/theming/image/background'), url('../../../core/img/background.png');
}
```

**Comment by severus-tux** [comment]
> 1. I'm assuming you're using apache here, so please correct me if I'm wrong. You can follow the steps from the documentation and switch to using "pretty urls", aka urls without index.php in them, https://docs.nextcloud.com/server/19/admin_manual/installation/source_installation.html#pretty-urls

Thanks. That solved the issue. Also, "pretty urls" is even better.
