### ISSUE TITLE
Problem with the Passman App

### ISSUE THREAD

**Issue by tidoni** [mwalbeck/nextcloud-breeze-dark#160]
Hi,
i am using the [Nextcloud Passman App](https://github.com/nextcloud/passman) an if the page where passman gets the image from uses a favicon with a transparent background, the "no Image available"-Image is displayed behind the actual logo.
If I disable the dark mode, this does not occur. Not sure if anyone here can fix this, or it needs to be fixed in the passman app.
For better understanding:
![LogoBad](https://user-images.githubusercontent.com/24697188/91577150-9bdb9e80-e948-11ea-8dfc-dcd810ccb2bf.PNG)
![LogoAlright](https://user-images.githubusercontent.com/24697188/91577751-7602c980-e949-11ea-90d1-e2a8490d31a0.PNG)

To reproduce this, the URL is: https://service.simplytel.de

If anyone has questions or any idea, id be happy for any feedback.

**Comment by mwalbeck** [comment]
Hi, thanks for reporting this. I would consider this a bug with the theme, I'll have a closer look and get it fixed.

**Comment by mwalbeck** [comment]
I've changed it so it mimics the default behavior of passman, so there is no longer any default icon which fixes this issue.
