### ISSUE TITLE
Thumbnail image in the settings

### ISSUE THREAD

**Issue by xXFreeFunXx** [mwalbeck/nextcloud-breeze-dark#161]
Only one suggestion in the basic settings:
To make it look consistent and to let the users know that there is still a theme. Currently it simply goes under because it is further down the list and since there is no preview image, many users overlook this theme.

**Your setup:**
 - Nextcloud version: 19.0.2
![image](https://user-images.githubusercontent.com/10706711/91594152-b2422400-e961-11ea-8a78-2e9086c82498.png)

Thank you for your loving work

**Comment by mwalbeck** [comment]
Thanks for your suggestion. It seems like a pretty good idea, I'll include it in the next release.

**Comment by mwalbeck** [comment]
Thanks again for the suggestion. It will be in 20.0.1 and 19.0.7.
