### ISSUE TITLE
GpxPod unstyled

### ISSUE THREAD

**Issue by a-mair** [mwalbeck/nextcloud-breeze-dark#165]
**Which app would you like to have styled**:
GpxPod: https://apps.nextcloud.com/apps/gpxpod

**Your setup (please complete the following information):**
 - Nextcloud version: 18.0.9

**Comment by mwalbeck** [comment]
Dark theme support was also added to this app by the author. I have look through it and couldn't find any issues.

**Comment by helmut72** [comment]
Compare routes isn't shown properly:

<img width="612" alt="Bildschirmfoto 2021-02-28 um 14 33 26" src="https://user-images.githubusercontent.com/1388751/109420314-05a93380-79d2-11eb-90f9-04617324079a.png">

**Comment by mwalbeck** [comment]
@helmut72 Thanks for letting me know, it will be fixed in the next release.
