### ISSUE TITLE
GpxEdit unstyled

### ISSUE THREAD

**Issue by a-mair** [mwalbeck/nextcloud-breeze-dark#167]
**Which app would you like to have styled**:
GpxEdit: https://apps.nextcloud.com/apps/gpxedit

**Your setup (please complete the following information):**
 - Nextcloud version: 18.0.9

**Comment by mwalbeck** [comment]
There hasn't been a proper release of this app for either NC 20 or 21, but when the app is updated then I'll make sure to add styling support for it.

**Comment by Synochy** [comment]
The app is now compatible with NC20 : https://gitlab.com/eneiluj/gpxedit-oc/-/issues/61
Is it possible to have it styled ?
Thanks by advance

**Comment by mwalbeck** [comment]
Thanks for letting me know! I just did the styling work, and it'll be included in the next release.
