### ISSUE TITLE
Regression: JSXC login buttons not themed anymore

### ISSUE THREAD

**Issue by poVoq** [mwalbeck/nextcloud-breeze-dark#169]
**Describe the bug**
![login_jsxc](https://user-images.githubusercontent.com/940360/95338442-75434880-08a2-11eb-9aa9-742664c27214.jpg)

**Expected behavior**
I am 95% sure that it was working until this recent update. But my memory might be playing tricks on me.

**Setup (please complete the following information):**
 - Nextcloud version: [e.g. 17.0.3]19.0.3
 - Theme version [e.g. 17.0.6] latest
 - Browser and browser version [e.g. Firefox 70, Chrome 72] Firefox latest on Linux

**Comment by mwalbeck** [comment]
You're most likely correct. I redid the core styling, to simplify it, and I must have missed this. Thanks for reporting.
