### ISSUE TITLE
 Cospend menu not styled anymore NC 20

### ISSUE THREAD

**Issue by Synochy** [mwalbeck/nextcloud-breeze-dark#170]
**Describe the bug**
The selection menus are not themed anymore.

**Screenshots**
![image](https://user-images.githubusercontent.com/20789073/95663248-1ba27e80-0b2d-11eb-8446-e50e4c7f7fb3.png)

**Setup (please complete the following information):**
 - Nextcloud version: 20
 - Theme version 19.0.5
 - Browser and browser version Firefox 81.0.1

**Comment by mwalbeck** [comment]
I had a look and with theme version 20.0.0, which I have just released, and I couldn't reproduce the issue. Can you check if it still an issue with that version?

**Comment by Synochy** [comment]
I just tested with the new version 20.0.0 and I still have the same issue.
I tested with firefox and google chrome without any add-on.

**Comment by mwalbeck** [comment]
Mhm, are you on Windows and/or using a light desktop theme or maybe a light browser theme?

**Comment by mwalbeck** [comment]
I had time to do a quick test and managed to replicate the issue on Windows and partially on KDE with the light theme. The issue here is the dropdown options are unthemed and relies on the browsers styling instead, which is partially based on the desktop theme on is using.

Thanks for reporting.

**Comment by Synochy** [comment]
I am on windows 10 with dark theme and dark theme also on firefox.

You are welcome
