### ISSUE TITLE
Border for input field is missing in Two Factor TOTP

### ISSUE THREAD

**Issue by DerKappenstricker** [mwalbeck/nextcloud-breeze-dark#172]
Since Theme version 19.0.5 no border is shown for TOTP input field on login screen. To reproduce see the attached screenshot.

Screenshot
![screenshot](https://user-images.githubusercontent.com/72970217/96239112-96412300-0f9f-11eb-8271-949582217c61.PNG)

Setup:
 - Nextcloud version: 19.0.3 + 19.0.4
 - Theme version: 19.0.5
 - Browser and browser version: Firefox 81.0, Safari 14.0

**Comment by mwalbeck** [comment]
Thanks for reporting this. It will be fixed in the next release.
