### ISSUE TITLE
Styling issue in calendar for current day in weekly and monthly view

### ISSUE THREAD

**Issue by spiezmaestro** [mwalbeck/nextcloud-breeze-dark#178]
**Describe the bug**
The current day in the weekly and monthly view have a slight styling issue:

Weekly view
![afbeelding](https://user-images.githubusercontent.com/57439282/97286873-33c01080-1844-11eb-8fe5-3aafbc3bc0b3.png)
Monthly view
![afbeelding](https://user-images.githubusercontent.com/57439282/97286993-581bed00-1844-11eb-9877-64c28089b816.png)

**Setup (please complete the following information):**
 - Nextcloud version: 20.0.1
 - Theme version: 20.0.0
 - Browser and browser version: Firefox 82.0
 - Calendar version: 2.1.2

Nothing too bad, but would be nice when it is fixed. Thx!

**Comment by mwalbeck** [comment]
Thanks for reporting, this is more of an issue with Calendar itself, so I've submitted a bug report with the project https://github.com/nextcloud/calendar/issues/2679

**Comment by mwalbeck** [comment]
A fix has been merged https://github.com/nextcloud/calendar/pull/2939 and should be included in the next release of Calendar.
