### ISSUE TITLE
Remove Top ribbon on dashabord screen NC 20

### ISSUE THREAD

**Issue by axheli** [mwalbeck/nextcloud-breeze-dark#179]
Dashboard with breeze dark app installed 
![image](https://user-images.githubusercontent.com/59488153/97596781-166d7c80-19d3-11eb-9953-c000e42acf15.png)

Dashboard without breeze dark app installed 

![image](https://user-images.githubusercontent.com/59488153/97596962-4d439280-19d3-11eb-93f0-74856ef79b21.png)

**Comment by mwalbeck** [comment]
Thanks for reporting, will be fixed in the next release.
