### ISSUE TITLE
Allow Custom Slogan and Name

### ISSUE THREAD

**Issue by SqueeZen** [mwalbeck/nextcloud-breeze-dark#18]
Hello, first of all, thank you for this almost perfect theme (it only misses theme for polls to be perfect).

I have only one small minor issue (similar to # 11): I can not change the slogan and name of my Nextcloud instance since I had to disable the Theming app to install this skin.

Is there a clean solution to change these elements?

Thank you, good luck!

**Comment by mwalbeck** [comment]
Hi, thank you for the kind words. I might be able to do something about styling for polls, but, for now, to the matter at hand. The way the slogan and name is changed with custom themes is through a file called defaults.php which is located at the root of the theme. Now I don't ship one with the theme as I had no need to change the defaults, so it made more sense to just remove it than having to make sure it was up to date.

I can add defaults.php to the .gitignore file so you can add your own, and still be able to easily update through git. You can find a version of it in themes/example in your Nextcloud directory. I can give you a hand, if needed, with customizing the defaults.php file for you, so you only have the necessary functions included for changing the name and slogan.

Let me know what you think.

**Comment by SqueeZen** [comment]
This is exactly the answer I needed!
Problem solved, thank you very much! ;)
