### ISSUE TITLE
Non-transparent header

### ISSUE THREAD

**Issue by yardbro** [mwalbeck/nextcloud-breeze-dark#182]
Can you please consider adding an option to toggle the transparent header with the new NC20 dashboard? I really liked the ability to have that not be the same color as the background :)

**Comment by mwalbeck** [comment]
Originally I didn't plan to directly provide a way to customise the theme in small ways, but instead refer to using the Custom CSS app. Though that is no longer an ideal solution so I'm currently considering how best to allow for customisation of this nature without adding a bunch of extra code to the theme, for each little customisation. So it's something that will be available at some point, but I can't say when.

The Custom CSS app may be able to help in the meantime with the caveat that any customisations made with it will apply globally no matter if the Breeze Dark theme is in use or not. If this is not a problem you can download it and add this CSS rule:
```
#body-user #header {
	background-color: var(--color-background-darker) !important;
}
```
That will set the header to the default header colour used in the rest of the theme.

**Comment by mwalbeck** [comment]
I plan to implement custom css functionality into the theme to resolve the issue of customisations being applied globally when you only want to modify something related to the theme. When that is implemented I would consider this resolved so I'm going to close this issue in favor of #204

**Comment by Fuseteam** [comment]
was just looking to have a transparent header on the dashboard
since the is has a custom background image, it does look a lot nicer
currently
![image](https://user-images.githubusercontent.com/10421851/107792242-aa214980-6d33-11eb-9016-798efc5764d0.png)
with transparent header
![image](https://user-images.githubusercontent.com/10421851/107792399-de950580-6d33-11eb-98c7-4b7c918a5d73.png)

**Comment by mwalbeck** [comment]
Hi @Fuseteam the transparent header is actually the proper default, but while fixing another bug I reintroduced the non-transparent header by accident. I have fixed the issue and that fix will be included in the next release.

**Comment by Fuseteam** [comment]
thanks @mwalbeck I'll look forward to the next release
