### ISSUE TITLE
Ugly view in new version Collabora Online 6.4

### ISSUE THREAD

**Issue by antiuser** [mwalbeck/nextcloud-breeze-dark#183]
**Describe the bug**
Panels view ugly with new Collabora Online 6.4 (black stripes of menu)
**To Reproduce**
Open any XLS file with enabled Breeze Dark theme

1. Go to 'any directory in web nextcloud interface'
2. Click on 'any XLS or ODS file'
3. See black stripes in any menu bar

**Expected behavior**
A white interface without any artifact or any better view

![Снимок экрана_2020-11-09_23-54-10](https://user-images.githubusercontent.com/5499424/98583900-eda88980-22e6-11eb-9065-f505ed5e1120.png)

**Setup (please complete the following information):**

-   Nextcloud version: [19.0.4]
-   Theme version: [19.0.7]
-   Browser and browser version: [Chrome 85.0.4183.102]

**Comment by mwalbeck** [comment]
I've had a look at the code and tested a few things, but there doesn't seem to be a solution or workaround, on my end, that isn't overly complicated. It would make more sense to handle this upstream. The official dark theme is also affected by this.

**Comment by mwalbeck** [comment]
I have created a fix that has just been merged into the Collabora Online app and is set to be backported. So this will be fixed whenever the next release of the Collabora app is.

https://github.com/nextcloud/richdocuments/pull/1394
