### ISSUE TITLE
TOTP login page not styled anymore

### ISSUE THREAD

**Issue by DerKappenstricker** [mwalbeck/nextcloud-breeze-dark#185]
The TOTP login page shows the default theme although Breeze Dark is enabled.

**Screenshots**

![image](https://user-images.githubusercontent.com/72970217/100140638-86b3d480-2e91-11eb-80a3-9e54b60ffcbe.png)

**Setup:**

-   Nextcloud version: 20.0.1 and 20.0.2
-   Theme version: 20.0.1
-   Browser and browser version: Safari 14.0.1, Firefox 83.0

**Comment by mwalbeck** [comment]
Thanks for reporting this. It seems the stylesheet for the login page isn't loaded on the totp page.
