### ISSUE TITLE
Fix main login screen background

### ISSUE THREAD

**Issue by axheli** [mwalbeck/nextcloud-breeze-dark#186]
Is there a way  to set it so it dose not affect the main login screen when having this app enabled
![image](https://user-images.githubusercontent.com/59488153/100253411-b3ee9a00-2f06-11eb-92e9-be391375524e.png)

**Comment by mwalbeck** [comment]
Yes, I recently added it, but I can see I forgot to update the readme with the option. If you go into the Theming section of the Admin settings in Nextcloud there will be an option to exclude the login page.

**Comment by axheli** [comment]
Sick! Thanks brother. Love it
