### ISSUE TITLE
Phone Sync App Messages Unreadable

### ISSUE THREAD

**Issue by rkeen9** [mwalbeck/nextcloud-breeze-dark#188]
**Describe the bug**
White text on white background for Phone Sync app.

**To Reproduce**

1. Install phone sync app on instance with Breeze preinstalled
2. Launch Phone sync
3. Open conversation

**Expected behavior**
Formatting that is consistent with other Breeze Dark stylized apps.

**Screenshots**
![image](https://user-images.githubusercontent.com/32402703/100639951-aeb89300-32ea-11eb-804c-3b1d07763b3f.png)

**Setup (please complete the following information):**

-   Nextcloud version: 19.0.3
-   Theme version: 19.0.7
-   Browser and browser version: Firefox 83.0

**Additional context**
Also observed on Firefox and Brave mobile browsers.

**Comment by mwalbeck** [comment]
Thanks for reporting this. Sorry it took a while but I had some trouble with the setup. The fix will be include in the next release.
