### ISSUE TITLE
Background Issue, Mail App

### ISSUE THREAD

**Issue by jkuester** [mwalbeck/nextcloud-breeze-dark#19]
First I would like to say thank you for a great theme! It looks awesome!

I am currently running into a bit of trouble in the NextCloud Mail app.  Everything looks fine except for in the navigation section on the left. When I expand a collapsed parent directory, the background for the expanded section is not styled correctly (it has a white background). 

Here is what things look like before the section is expanded:
![before](https://user-images.githubusercontent.com/8441903/38176697-3181cf2c-35b9-11e8-952d-dd5ba82b1991.png)

And here is what things look like after the section is expanded:
![after](https://user-images.githubusercontent.com/8441903/38176698-3d1d5e78-35b9-11e8-912c-dff57b1bc5c2.png)
In this picture I highlighted the "All" directory with the mouse, but the rest of the white space contains different directories that cannot be seen since the text color is the same as the background.

After some digging, I found that if I unchecked the background image being set as seen below, then the theme's proper background would get picked up:
![details](https://user-images.githubusercontent.com/8441903/38176771-830d5d7e-35ba-11e8-9152-3559fc1699b5.png)

With this in mind, I tried to just add this to my _mail.scss file:
```
#app-navigation .collapsible.open {
  background-image: none;
}
```
But it had no effect. Admittedly, I am not really familiar with scss, so this might not be the right change, or I might have been putting it in the wrong spot.  (Or maybe I just missed some step in getting my NextCloud to pickup the change.  I restarted my NextCloud service and cleared the cache in my browser.) Any suggestions you might have would be greatly appreciated!  

Thank you!

NextCloud Version: 12.0.5
nextcloud-breese-dark Version: 13.0.2

**Comment by mwalbeck** [comment]
I'm glad you like the theme and thanks for reporting this issue. 

I've looked into it and there is both a problem with the mail app in Nextcloud 13 and Nextcloud 12. The problems are slightly different for the 2 versions of Nextcloud so I'll release a fix for both. Now I can see you're using theme version 13.0.2, so I would like to ask you to change to the newest 12.0.x version when I release the fix. The 12 train should also work better with Nextcloud 12. If there is a specific reason why you are using the theme version for NC 13 let me know and I can backport the changes for NC 12.

If you are using git you can change to branch 12 to only get theme updates for NC 12, or you can download the latest version from the release page.

**Comment by jkuester** [comment]
I pulled down your changes (and switched to branch 12). Now everything looks great!  Thank you!

BTW, the only reason I was on 13.0.2 was because I blindly pulled the latest from master in an attempt to see if the issue I was having was because I was on an older version.
