### ISSUE TITLE
Errors in log after update

### ISSUE THREAD

**Issue by UspAN** [mwalbeck/nextcloud-breeze-dark#193]
**Describe the bug**
Everything works fine but log is full of these errors after last update:
{"reqId":"DIkFx9FfNFOdazsxE4TS","level":3,"time":"2020-12-22T08:45:55+00:00","remoteAddr":"192.168.1.1","user":"***","app":"PHP","method":"POST","url":"/index.php/settings/apps/disable","message":{"Exception":"Error","Message":"Undefined variable: user at /var/www/nextcloud/apps2/breezedark/lib/AppInfo/Application.php#64","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps2/breezedark/lib/AppInfo/Application.php","line":64,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/nextcloud/apps2/breezedark/appinfo/app.php","line":28,"function":"doTheming","class":"OCA\\BreezeDark\\AppInfo\\Application","type":"->"},{"file":"/var/www/nextcloud/lib/private/legacy/OC_App.php","line":266,"args":["/var/www/nextcloud/apps2/breezedark/appinfo/app.php"],"function":"require_once"},{"file":"/var/www/nextcloud/lib/private/legacy/OC_App.php","line":155,"function":"requireAppFile","class":"OC_App","type":"::"},{"file":"/var/www/nextcloud/lib/private/legacy/OC_App.php","line":128,"function":"loadApp","class":"OC_App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":995,"function":"loadApps","class":"OC_App","type":"::"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36","version":"19.0.6.2","id":"5fe1b2a0c32f6"}
{"reqId":"DIkFx9FfNFOdazsxE4TS","level":3,"time":"2020-12-22T08:45:55+00:00","remoteAddr":"192.168.1.1","user":"***","app":"PHP","method":"POST","url":"/index.php/settings/apps/disable","message":{"Exception":"Error","Message":"Undefined variable: user at /var/www/nextcloud/apps2/breezedark/lib/AppInfo/Application.php#60","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps2/breezedark/lib/AppInfo/Application.php","line":60,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/nextcloud/apps2/breezedark/appinfo/app.php","line":28,"function":"doTheming","class":"OCA\\BreezeDark\\AppInfo\\Application","type":"->"},{"file":"/var/www/nextcloud/lib/private/legacy/OC_App.php","line":266,"args":["/var/www/nextcloud/apps2/breezedark/appinfo/app.php"],"function":"require_once"},{"file":"/var/www/nextcloud/lib/private/legacy/OC_App.php","line":155,"function":"requireAppFile","class":"OC_App","type":"::"},{"file":"/var/www/nextcloud/lib/private/legacy/OC_App.php","line":128,"function":"loadApp","class":"OC_App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":995,"function":"loadApps","class":"OC_App","type":"::"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36","version":"19.0.6.2","id":"5fe1b2a0c3336"}

**Setup:**

-   Nextcloud version: 19.0.6.2
-   Theme version: 19.0.8

**Comment by mwalbeck** [comment]
Thanks for reporting this. I've just published a new release that should fix the issue. Sorry for the trouble.
