### ISSUE TITLE
Clarification in Usage Docs

### ISSUE THREAD

**Issue by OvertCoffee** [mwalbeck/nextcloud-breeze-dark#194]
On the [app's page](https://apps.nextcloud.com/apps/breezedark) you give some brief instruction on how to implement this theme. I may just be a bit dense, but it took me a while to figure out you need to activate the Theming app to add the theming option in settings. I think changing this line:

```
After you install the theme, you need to enable it. There a 2 options for this, a global and a personal one.
```

to:

```
After you install the theme (and enable the Theming app), you need to enable it. There a 2 options for this, a global and a personal one.
```

might avoid that same confusion with newbies in the future. Thanks.

**Comment by mwalbeck** [comment]
Thanks for letting me know. I wasn't actually aware of this. I looked a bit more into it and it also applies to the personal settings, where you need the accessibility app enable for the setting to show up.

I had a look to see if I could fix the issue but currently it seems the only solution is to put them into a different section in the settings, which I prefer not to do as they kind of belong where they currently are.

I'll include a note about it in the relevant places.
