### ISSUE TITLE
Black bar around the logo on login screen for password protected shared links when "Theme the login page" is activated

### ISSUE THREAD

**Issue by luddinho** [mwalbeck/nextcloud-breeze-dark#195]
**Description**
When the Breeze Dark theme is activated and the user creates a password protected shared file link, the login screen displays a black (dark) bar around the logo.

**Reproduce**

_Prerequisites:_
The Administrator has enabled the "Enable Breeze Dark theme by default" and "Theme the login page".

1. Administrator --> settings --> Theming --> enable ("Enable Breeze Dark theme by default" & "Theme the login page")
2. Login as User
3. Go to files
4. Create a password protected shared file link of an existing or a new file
5. log off from the Nextcloud instance
6. Use the file link either from the clippboard or from the received email (depends on the link creation)
7. When accessing the Nextcloud instance via the shared file link the logo above the password field is wrapped in a dark bar.
8. When the Administrator disable "Theme the login page" the issue remains
9. Only when the Administrator disable "Enable Breeze Dark theme by default" the problem is not present.

**Expected behavior**
The logo on the login screen shall be on a transparent layer that the underlaying background image will be displayed.

**Screenshots**
Please see the screenshot below.

![image](https://user-images.githubusercontent.com/76713238/103251815-c5e6b100-497a-11eb-95aa-553595406f4d.png)

**Setup (please complete the following information)**
-   Nextcloud version: 20.0.4
-   Theme version: 20.0.2
-   Browser and browser version: Microsoft Edge 87.0.664.66 / Firefox 83.0 (64-Bit) / Safari 14.0.2

**Additional context**
 - Problem only occurs on Nextcloud 20, with a Nextcloud instance 19.0.6 there is no issue.
 - Apache 2.4
 - PHP 7.3
 - independently from the background image, either with default background or customized picture via theming app "Theming 1.11.0"

**Comment by mwalbeck** [comment]
Thanks for reporting this and thank you for the very detailed bug report. The fix will be in the next release.

**Comment by luddinho** [comment]
You´re welcome, Magnus! I just filled the bug report template as reqeusted. In my opinion, the better the discription the easier the issue can be identified and solved from the developer.
And many thanks to you publishing such a great theming app for Nextcloud. I really like it!

**Comment by mwalbeck** [comment]
I totally agree, it's just not often to see that level of detail so I feel it's important, as a maintainer, to mention it and say thank you, because it really does make a difference. I'm glad you enjoy the theme.
