### ISSUE TITLE
News app - compact article view odd row color to bright

### ISSUE THREAD

**Issue by efelon** [mwalbeck/nextcloud-breeze-dark#197]
**Describe the bug**
Since the latest update of the news app, alternating row colors are introduced in the compact article list. The contrast of the selected color in the dark theme is way to high (see screenshot).

**To Reproduce**
1. Enable breeze dark theme
2. Click on 'News'
3. Enable 'Compact view'

**Expected behavior**
The blue color of every odd numbered row should be much darker.
_(Not even necessary IMHO)_

**Screenshots**
![image](https://user-images.githubusercontent.com/10722552/104620813-b14f2c00-568f-11eb-9725-38abba0d44bd.png)

**Setup (please complete the following information):**

-   Nextcloud version: 20.0.5
-   Theme version: up to date (can check later if needed)
-   Browser and browser version: [e.g. Firefox 84.0.2]

**Comment by mwalbeck** [comment]
Thanks for reporting this. I'm aware of the issue, but I'm currently awaiting a decision by News app devs on how they want to move forward with the design. You can have a look at the relevant issue here https://github.com/nextcloud/news/issues/1012

In the meantime, if you would like to disable the alternating row colour, then you can install the Custom CSS app and add the following css rule in the Theming section of the settings:
```
.app-news #app-content .compact li.item:nth-child(2n+1) div.utils {
    background-color: var(--color-main-background);
}
```

**Comment by mwalbeck** [comment]
The News app devs have decided to revert the change so this will be fixed with the next release of News.

**Comment by efelon** [comment]
Many thanks @mwalbeck for chasing after this one, even though it comes from another app.
