### ISSUE TITLE
Changing colours doesn't work

### ISSUE THREAD

**Issue by rodude123** [mwalbeck/nextcloud-breeze-dark#198]
I tried to modify the color.scss file but the colours won't load in my nextcloud. I tried disabling the app and reenabling the app but that didn't work. I also tried to do a repair from maintenance using `sudo -u www-data php occ maintenance:repair` 

-   Nextcloud version: 20.0.4

**Comment by mwalbeck** [comment]
The problems you are most likely running into is that you also need to make the same change in the guest.css file then it should work as intended.

Let me know if you run into any other issues.

**Comment by rodude123** [comment]
Where is the guest.csss file? do you know?

**Comment by rodude123** [comment]
Could you tell me what to edit in the guest.css file please

**Comment by rodude123** [comment]
Thanks, it worked wonders!

**Comment by rodude123** [comment]
I updated the app to a later revision and updated my nextcloud to 21.0.2 and re changed the colours in `guest.css` and `_color-variables.scss` but nothing really worked they are still the blue colour. I changed the `--color-plasma-blue` and `--color-hover-blue`

**Comment by mwalbeck** [comment]
I'm assuming you got it sorted. You can also have a look at the custom css functionality i've built into the theme, then you can make your changes in an upgrade safe way. You can find the option to add the custom css under Admin settings > Theming there should a custom css box for Breeze Dark.

A quick example, if you want to change plasma-blue and hover-blue to black you can add the following css:
```
:root {
    --color-plasma-blue: #000;
    --color-hover-blue: #000;
}
```

**Comment by rodude123** [comment]
Yes all working fine now again.
