### ISSUE TITLE
nextcloud snap installation

### ISSUE THREAD

**Issue by edrimon** [mwalbeck/nextcloud-breeze-dark#199]
Hi, it seems that the background is white, the fonts in white as well, so practically no message can be read when using the Mail app.

![image](https://user-images.githubusercontent.com/1180528/105326422-6628a200-5bd6-11eb-97b2-893fdea6df8d.png)

content can be seen only if you start highlighting some text using the mouse:

![image](https://user-images.githubusercontent.com/1180528/105326626-9f611200-5bd6-11eb-9f17-31c941d76841.png)

**Comment by mwalbeck** [comment]
Thanks for reporting.

This is the same issue as #196. You can have a look there and the relevant issue in the Mail app repo for more info about the issue.

I'm going to close this issue in favour of the other one.
