### ISSUE TITLE
Styling for Apps

### ISSUE THREAD

**Issue by mwalbeck** [mwalbeck/nextcloud-breeze-dark#2]
Here you can see the progress for the styling of Nextcloud apps for Nextcloud 12. Apps not on the list is currently not planned for styling. If you would like a Nextcloud app which is not on the list to be styled please open a new issue. For more info on how to contribute please checkout [CONTRIBUTING.md](https://github.com/mwalbeck/nextcloud-breeze-dark/blob/master/CONTRIBUTING.md).

Currently styled:

- [x] Nextcloud Core apps
- [x] Calendar
- [x] Contacts
- [x] News
- [x] Notes
- [x] Audio Player
- [x] Phone Sync
- [x] Mail
- [x] Music
- [x] Deleted files
- [x] External sites
- [x] File access control
- [x] Files automated tagging
- [x] Retention
- [x] Two Factor TOTP Provider
- [x] Two Factor U2F
- [x] Brute-force settings
- [x] Circles
- [x] Group Folders
- [x] Impersonate
- [x] Social Sharing Via *
- [x] Tasks
- [x] Checksum
- [x] Registration
- [x] Passman
- [x] QOwnNotesAPI
- [x] Bookmarks
- [x] Quota warning
- [x] Keeweb
- [x] Radio
- [x] Metadata
- [x] User Account Deletion
- [x] Flow Upload
- [x] Deck
- [x] Collabora Online (Currently no plans to make a dark themed version of the editor, but it works as intend)
- [x] Announcement Center (icons are taken from the core theme instead of the custom theme, so they are black)

Planned: 
- [ ] Talk
- [ ] JavaScript XMPP Chat

**Comment by MiGo2000** [comment]
Thank you for your work, I like your theme and use it.
I use the app 'Deck' and saw, that the letter color of comments is now lightgray on white, not too good to read. Is it possible to add it to your planned work?
Thanks!

**Comment by mwalbeck** [comment]
Thank you for the using the theme. I'll see what I can do about it.

**Comment by mwalbeck** [comment]
I've made a new release for NC12 with styling for the Deck app as well as a new release with styling for NC13

**Comment by MiGo2000** [comment]
Great, Magnus!
I just updated to NC13 and will see.
Thanks!
Michael


Am 6. Februar 2018 17:56:29 schrieb Magnus Walbeck <notifications@github.com>:

**Comment by adx442** [comment]
The newest is working very well on NC 13, thank you very much for continuing your work on this theme.

I'd like to see the FullTextSearch (Nextant replacement) app in the list.  Right now, they use a custom Search icon to the left of the Contacts search icon, and with the theme in place, it's not available (e.g., if you use FullTextSearch and this theme, you can't search).  

Thanks!

**Comment by mwalbeck** [comment]
Moved list to [wiki page](https://github.com/mwalbeck/nextcloud-breeze-dark/wiki/App-Styling)

For new request please open a new issue
