### ISSUE TITLE
Tasks: Some elements are unreadable

### ISSUE THREAD

**Issue by rEnr3n** [mwalbeck/nextcloud-breeze-dark#20]
The checkbox at the left side of the text is barely seen. The text on start/due date is unreadable.
![screenshot_2018-04-28_14-22-32](https://user-images.githubusercontent.com/18730618/39392985-39c0267c-4af2-11e8-8d9f-a78ff95daacc.png)

The weekdays are unreadable when hovering mouse on calendar.
![1](https://user-images.githubusercontent.com/18730618/39392994-5af92352-4af2-11e8-9753-409ee3c69158.png)

The same happens with hours and minutes.
![2](https://user-images.githubusercontent.com/18730618/39392995-5b354896-4af2-11e8-8919-34e9798b1145.png)

Priority number is unreadable.
![3](https://user-images.githubusercontent.com/18730618/39392996-5b6cdf0e-4af2-11e8-8502-2ee6e0bf7ae0.png)

Progress percentage is unreadable.
![4](https://user-images.githubusercontent.com/18730618/39392997-5bd14764-4af2-11e8-9a85-2596e3102c1c.png)

**Comment by adx442** [comment]
Tacking onto this, but with regards to the FullTextSearch plugin results.  The primary results are visible, but the contextual results below are unreadable without highlighting.

![2018-05-31_100611](https://user-images.githubusercontent.com/31186396/40790398-7431042a-64ba-11e8-8bc2-76c38d389ad2.png)

**Comment by mwalbeck** [comment]
@adx442 Can I ask you to open a new issue instead.

**Comment by mwalbeck** [comment]
Fixed in 13.0.3, thanks for reporting.
