### ISSUE TITLE
Userstyle availability

### ISSUE THREAD

**Issue by ggurbet** [mwalbeck/nextcloud-breeze-dark#200]
Hello. Is there a Userstyle version of this style? If not, are there any plans for one in the future? Thanks.

**Comment by mwalbeck** [comment]
Hi,

No, currently there is no userstyles version. I also don't have any plans at this time to make one. Though I don't see any issues with one being made, if someone is interested in doing it.

**Comment by ggurbet** [comment]
Thank you for the response!
