### ISSUE TITLE
styling the circle description is missing

### ISSUE THREAD

**Issue by Yann-974** [mwalbeck/nextcloud-breeze-dark#201]
In the Circles app, when there is a description, it is shown in a white color over a white frame.

![image](https://user-images.githubusercontent.com/78294159/106416641-537e5a80-646b-11eb-9cc4-3a7ada0f3392.png)

-   Nextcloud version: 20.0.1
-   Theme version: 20.0.3
-   Browser and browser version: Firefox 84.02, Chromium Version 87.0.4280.66

**Comment by mwalbeck** [comment]
Thanks for reporting this. The fix will be in the next release which should be out shortly.
