### ISSUE TITLE
Add custom styling functionality

### ISSUE THREAD

**Issue by mwalbeck** [mwalbeck/nextcloud-breeze-dark#204]
**What feature would you like to see added to the theme?**:
Custom styling functionality

**Your setup (please complete the following information):**

-   Nextcloud version: 20.0.7

**Comment by mwalbeck** [comment]
Related to #182 and #184

**Comment by tiotrom** [comment]
I'd love to see that. For now I am using custom CSS to do that. And I run into issues such as:
```
.app-navigation-entry.active {
	background-color: var(--color-primary-light) !important;
}
```
Using !important in the original code, makes me unable to change that value... :P

**Comment by mwalbeck** [comment]
This most likely won't fix that issue as the implementation will be very similar to the Custom CSS app. The purpose of adding this to the theme is to allow for customisations that won't affect the default themes.

The simple way to solve that issue is most likely just to increase the specificity of the selector. In your circumstance you can most likely use this instead and it should work
```
#app-navigation .app-navigation-entry.active {
	background-color: var(--color-primary-light) !important;
}
```

**Comment by tiotrom** [comment]
I see.
`
#app-navigation .app-navigation-entry.active {
	background-color: var(--color-primary-light) !important;
}
`
Didn't do the trick. I'll try more options, but of you have more in mind let me know please.

**Comment by mwalbeck** [comment]
If you can tell me where and what app, then I can most likely help. It heavily depends on the HTML structure, so the previous suggestion I gave was more of a guess based on the name of the class.

**Comment by tiotrom** [comment]
Ah yes that worked. Thanks!
