### ISSUE TITLE
Passwords - Sidebar is rendered wrong

### ISSUE THREAD

**Issue by mikshepard** [mwalbeck/nextcloud-breeze-dark#21]
The [passwords app](https://apps.nextcloud.com/apps/passwords) is not rendering correctly.  The sidebar is filled with random characters.  Could support for this be added?  

![image](https://user-images.githubusercontent.com/3514599/39450919-8e5bcdac-4c92-11e8-88e1-b7269d2897ac.png)

Many thanks,

**Comment by mwalbeck** [comment]
I added styling for Passwords with the latest release.

**Comment by SqueeZen** [comment]
Hello,

Same issue with sidebar from version 14.0.2 :
![image 1](https://user-images.githubusercontent.com/12959697/47914255-324eee00-de9f-11e8-892e-889051eb7af3.png)

Thanks !

**Comment by mwalbeck** [comment]
Hi, could I ask you to open a new issue, you can refer back to this one but it makes it easier for me to keep track of things.
