### ISSUE TITLE
Quicknotes Styling

### ISSUE THREAD

**Issue by EV21** [mwalbeck/nextcloud-breeze-dark#22]
:page_facing_up: Quicknotes is new in the [Nextcloud App Store](https://apps.nextcloud.com/apps/quicknotes)
[:octocat: Quicknotes Git-Repo](https://github.com/matiasdelellis/quicknotes)
Maybe it could be a good replacement for the "Notes" :notebook: app, at least for the "quick" notes :fast_forward: 

It needs some new Styling- background and font-color

It would be nice if someone likes to fix this.

**Comment by mwalbeck** [comment]
I added styling for it in the latest release.
