### ISSUE TITLE
Announcement icon on Dashboard stays black

### ISSUE THREAD

**Issue by MarcMichalsky** [mwalbeck/nextcloud-breeze-dark#222]
The announcement icon on the dashboard does not turn bright like the others.

Maybe this has something to do with its class that is named `icon-announcementcenter-dark`?

![Screenshot_2021-03-05 Dashboard - Marc Michalsky](https://user-images.githubusercontent.com/24728186/110143889-05e16e80-7dd8-11eb-93a6-dc7e4e616147.png)

**Comment by mwalbeck** [comment]
Thanks for reporting.

The css rule overriding the icon was scoped only for the announcement center app, so it just needed to be applied globally instead.

**Comment by MarcMichalsky** [comment]
Thanks for fixing it!
