### ISSUE TITLE
FullTextSearch results - context portion unreadable

### ISSUE THREAD

**Issue by adx442** [mwalbeck/nextcloud-breeze-dark#23]
Version: Nextcloud 13.04
FullTextSearch versions: current trifecta
Expected behavior: File names and the context entry of the search result are both readable using the theme
Current behavior:  File names are perfectly readable, but the context entry below the file name is unreadable without highlighting

I tested using an incognito window and a fresh clone of the git just to be sure.

![40790398-7431042a-64ba-11e8-8bc2-76c38d389ad2](https://user-images.githubusercontent.com/31186396/41269616-cc7c564c-6dcb-11e8-8db2-f9b83a88cc1e.png)

In the other issue, it was stated that this was resolved for 13.03, but it's behaving the same way in 13.04 (I skipped 13.03, was not able to verify). 

Thank you!

**Comment by mwalbeck** [comment]
Sorry about the confusion, but what I said in the other issue was specific to that issue and not related to this one.

Right now I don't have an easy way to setup the required server component, so if you or anyone else can give a hand I'll be glad to add the changes. Otherwise I'll get to it when I have time to set everything up.

**Comment by adx442** [comment]
Hi Magnus, this appears to be resolved.  The context entries are now a slightly darker grey than the file name entry.  

In the future for issues related to plugins, if you would find shell access and a local account on my system, I'm happy to provide it ... it's snapshotted and virtualized, and can be walked back easily.

**Comment by mwalbeck** [comment]
Great, let me know if you find any other issues.

The main issue is with plugins that I don't use, that have a specific server component. I'll consider your offer the next time a styling issue with FullTextSearch pops up.
