### ISSUE TITLE
Cospend Styling bug when adding new project

### ISSUE THREAD

**Issue by Synochy** [mwalbeck/nextcloud-breeze-dark#231]
**Describe the bug**
When clicking add a new project in the app Cospend, icon is buging (see screenshot)

**To Reproduce**

1. Go to Cospend
2. Click on Add new project

**Screenshots**
![Capture d’écran 2021-03-15 082057](https://user-images.githubusercontent.com/20789073/111117129-635b8500-8567-11eb-90d6-bc432c5a8e05.jpg)

**Setup (please complete the following information):**

-   Nextcloud version: 21.0.0
-   Theme version: 21.0.3
-   Browser and browser version: Firefox 86.0.1
-   Cospend version : 1.2.9

**Comment by mwalbeck** [comment]
Thanks for reporting this. It should be fixed in the latest release.
