### ISSUE TITLE
Calendar list view issue

### ISSUE THREAD

**Issue by lambdaZ** [mwalbeck/nextcloud-breeze-dark#232]
I discovered some issue with the calendar app. When you switch to list view and place the mouse pointer on any list element the highlight color is too bright and the row is unreadable. Like on attached image.
![изображение](https://user-images.githubusercontent.com/1017969/111206969-241a4c00-85da-11eb-9b9d-a2e8c325c9b0.png)

**Comment by mwalbeck** [comment]
Thanks for reporting. This is also an issue with the default dark theme so I'll try and get it fixed upstream in Calendar instead.

**Comment by mwalbeck** [comment]
It has now been fixed in Calendar and the fix should be available in the next release.
