### ISSUE TITLE
LDAP app needs styling.

### ISSUE THREAD

**Issue by kendokan** [mwalbeck/nextcloud-breeze-dark#24]
Nextcloud Version 13.0.4
Theme Version 13.0.2
Firefox Version 60.0.2

Most of it looks fine, except for the Advanced settings which are nearly illegible.

![screenshot_1](https://user-images.githubusercontent.com/3757437/41510097-4fced146-7213-11e8-9f84-de4c23f2b134.png)

**Comment by mwalbeck** [comment]
Should be fixed with the latest update.
