### ISSUE TITLE
Icon transparent background

### ISSUE THREAD

**Issue by Valdnet** [mwalbeck/nextcloud-breeze-dark#241]
**Describe the bug**
Transparent background of the icons.

**To Reproduce**

1. Select "Files".
2. Move the mouse cursor over "Sharing".

Two icons visible. One under the other.

**Screenshots**
![obraz](https://user-images.githubusercontent.com/47037905/112994621-bb4eda00-916a-11eb-8090-ab05d02ca427.png)

**Setup (please complete the following information):**

-   Nextcloud version: 21.0.0
-   Theme version: 21.0.5
-   Browser and browser version: Firefox 87.0

**Comment by mwalbeck** [comment]
Thanks for reporting.

The hover background being transparent is intentional, but I have fixed the sharing icon being shown when hovering over "Sharing".
