### ISSUE TITLE
contacts icon in top bar is black

### ISSUE THREAD

**Issue by florealcab** [mwalbeck/nextcloud-breeze-dark#243]
**Describe the bug**
The contact icon on the right of the top bar (just before the avatar) is black, sohas a bad visibility.

**To Reproduce**

1. Open Nextcloud

**Expected behavior**
The icon should be on a light color, like other icons

**Screenshots**
![Illustration](https://i.postimg.cc/rsTycD3W/bug-nextcloud-dark.png)

**Setup (please complete the following information):**

-   Nextcloud version: 21.0.1
-   Theme version: 21.0.6
-   Browser and browser version: Firefox 87.0

**Comment by florealcab** [comment]
Oh, I just found the reason of the bug.

I enabled the official nextcloud dark theme inaddition to this breeze dark theme, which cause the bug. I just have to enable only this theme and the problem is gone. My bad!

**Comment by mwalbeck** [comment]
No worries.

Sometimes it can happen when just the Breeze Dark theme is enabled but that is usually because of some caching issue and can usually be fixed with a Ctrl+F5.

Cheers!
