### ISSUE TITLE
Change link color

### ISSUE THREAD

**Issue by HieronymusCH** [mwalbeck/nextcloud-breeze-dark#245]
**What feature would you like to see added to the theme?**:
in general

**Your setup (please complete the following information):**

-   Nextcloud version: 21.0.1

Hello o/

it would be an improvement to change the HTML link color from the standard blue to something brighter to increase contrast visibility, or to let the user set a personally chosen color.

**Comment by mwalbeck** [comment]
I have added a new link colour which improves the contrast and it will be available in the next release.
