### ISSUE TITLE
Passman Styling

### ISSUE THREAD

**Issue by RhvsW** [mwalbeck/nextcloud-breeze-dark#25]
https://apps.nextcloud.com/apps/passman

It's already pretty close, just a few white spots and out of place icons.

**Comment by mwalbeck** [comment]
Hi, could you include some screenshots of the styling problems, or a pointer to where in the app you have noticed them?

**Comment by RhvsW** [comment]
Hey yeah,

On the main page of a vault:
![image](https://user-images.githubusercontent.com/7466824/42030392-9010e20c-7aca-11e8-9938-5e88e02f95b3.png)

The add credential page:

![image](https://user-images.githubusercontent.com/7466824/42030408-9d56ba72-7aca-11e8-83cc-a4935c195778.png)

**Comment by mwalbeck** [comment]
Thanks, what Nextcloud and theme version are you using?

**Comment by mwalbeck** [comment]
I found out why I didn't see the same problems as you. It seems the version of passman you are using is the latest master, which is different from the current stable release on the nextcloud app store/github release page.

**Comment by RhvsW** [comment]
Ah that makes a lot of sense, I went with git master as the latest stable on the store is pretty damn outdated. Should have given you that version number.

**Comment by mwalbeck** [comment]
I mainly fixed the color issue in the theming for Passman. The rest are issue that hopefully will be fixed by the Passman developers, especially since this version of Passman is still under development.
