### ISSUE TITLE
Files Right Click doesn't have a css file

### ISSUE THREAD

**Issue by Ryonez** [mwalbeck/nextcloud-breeze-dark#26]
Hey, I'm ducking in because the app [Files Right Click](https://apps.nextcloud.com/apps/files_rightclick) doesn't seem to be styled, and the text colors could use some work:
![image](https://user-images.githubusercontent.com/16157130/42410993-ba540bb4-8247-11e8-8a75-d003a0ede8ca.png)

Would you mind having a look at this please? Cheers.

**Comment by mwalbeck** [comment]
Should be fixed with the latest release

**Comment by Ryonez** [comment]
Looks good, thank you.
