### ISSUE TITLE
still dark after disable and deactivation

### ISSUE THREAD

**Issue by Matyoto** [mwalbeck/nextcloud-breeze-dark#270]
I disabled the breeze dark in personal and admin settings and also deactivated the app. But sometimes I'm still seeing the dark background on shared links.

NC 22.1.1
Breeze dark 22.0.1
OSX 10.14.6
Safari 14.1.2

**Comment by mwalbeck** [comment]
Hi,

Could you try and do a CMD+F5 and see if that fixes the issue, if not could you post a screenshot of the issue?

**Comment by Matyoto** [comment]
Hi! I found out, that the issue was not related to "breeze dark".
I have my general appearance in OSX set to dark on one computer and I recently upgraded Nextcloud from version 17 to 21. In the older version, the background was always white in Nextcloud, but the new version will change the background depending on the OSX version. So no issue with breeze dark, then. :)

**Comment by mwalbeck** [comment]
Ahh, yes, newer versions of Nextcloud adept to your system theme unless you have made a conscious choice in the Nextcloud user settings.

Cheers!
