### ISSUE TITLE
Could not download app breezedark

### ISSUE THREAD

**Issue by alduccino** [mwalbeck/nextcloud-breeze-dark#277]
Hi,
when i click on activate the appp i get the message : Could not download app breezedark.

**Screenshots**
[https://i.ibb.co/nz44zLb/breeze-dark-nextcloud.jpg](url)

**Setup
-   Nextcloud version: 22.2.0
-   Theme version: 22.0.2

when i check the logs on nextcloud i get this : 

Exception: Could not download app 
/public_html/cloud/apps/settings/lib/Controller/AppSettingsController.php - line 444:OC\Installer->downloadApp("breezedark")

/public_html/cloud/lib/private/AppFramework/Http/Dispatcher.php - line 217:OCA\Settings\Controller\AppSettingsController->enableApps([ "breezedark"], [])

/public_html/cloud/lib/private/AppFramework/Http/Dispatcher.php - line 126:OC\AppFramework\Http\Dispatcher->executeController(OCA\Settings ... {}, "enableApps")

/public_html/cloud/lib/private/AppFramework/App.php - line 156:OC\AppFramework\Http\Dispatcher->dispatch(OCA\Settings ... {}, "enableApps")

/public_html/cloud/lib/private/Route/Router.php - line 301:OC\AppFramework\App::main("OCA\\Settin ... r", "enableApps", OC\AppFramew ... {}, { _route: "s ... "})

/public_html/cloud/lib/base.php - line 1000:OC\Route\Router->match("/settings/apps/enable")

/public_html/cloud/index.php - line 36:OC::handleRequest()

**Comment by mwalbeck** [comment]
I don't believe this is related to the breeze dark app itself, so I'll close the issue for now. You're welcome to reopen the issue if there is any new information on the issue.
