### ISSUE TITLE
Breeze Dark Won't Enable on Google Chrome

### ISSUE THREAD

**Issue by entropylabs** [mwalbeck/nextcloud-breeze-dark#284]
Hi Guys - been loving Breeze Dark on Nextcloud on Firefox - but for some reason, I can't get to enable itself on Google Chrome Stable (Version 95.0.4638.69 (Official Build) (64-bit).

Just curious if this is a known issue or there is something I need to change. Have tried deleting and re-enabling but again, it only shows up on Firefox. 

Thanks for the great work, guys!

**Comment by mwalbeck** [comment]
Hi,

Thank you for the kind words! I just have 2 questions to get started:

What OS are you running? And what Breeze Dark options have you enabled in `Settings > Accessibility > Breeze Dark` and in `Settings > Theming > Breeze Dark`?

**Comment by entropylabs** [comment]
Sure thing. I'm on Arch Linux and yes, I've set both areas to have 'Breeze Dark' toggled on. Thanks!

**Comment by mwalbeck** [comment]
Is this setting turned on? 
![image](https://user-images.githubusercontent.com/19759293/142237325-23aed22a-083d-4dff-b91d-ad73ce20b277.png)

**Comment by entropylabs** [comment]
Yes it is. Should it be turned off?

**Comment by entropylabs** [comment]
That did it! I toggled that off in the accessibility section. Thanks so much for that!

**Comment by mwalbeck** [comment]
Not necessarily but it's probably the cause of it. When using that setting either your browser has to be set to use a Dark theme, or your desktop theme should be a dark theme.

And if both apply to you, Chrome is most likely not reporting that which means the theme won't activate with that setting turned on.
