### ISSUE TITLE
Breeze Dark theme not applying on Nextcloud 22.2.3

### ISSUE THREAD

**Issue by pacholoamit** [mwalbeck/nextcloud-breeze-dark#286]
**Describe the bug**
I deployed the latest [official Nextcloud docker image](https://hub.docker.com/_/nextcloud) and I tried enabling Breeze dark both Globally & on the Personal configuration... Please see attached images below

However

I may be an idiot and didn't enable it properly

**To Reproduce**

1. Install the Nextcloud Breeze Dark theme through the app store
2. enable Breeze dark globally via Admin settings > Theming > Breeze Dark and/or;
3. enable it Personally through Personal settings > Accessibility > Breeze Dark

**Expected behavior**
I expect the Nextcloud theme to be adjusted to Breeze Dark

**Screenshots**

### Global
Admin settings > Theming > Breeze Dark

![image](https://user-images.githubusercontent.com/69985528/142768228-88842e4f-bd2e-4630-ada4-309150bfc88d.png)

### Personal
Personal settings > Accessibility > Breeze Dark

![image](https://user-images.githubusercontent.com/69985528/142768287-e8f4f209-e8c6-42a8-8e6e-47890398f71b.png)

**Setup (please complete the following information):**

-   Nextcloud version: 22.2.3
-   Theme version: 22.1.0
-   Browser and browser version: Chromium

**Additional context**

I've successfully configured Nextcloud for use with both MariaDB & Redis

**Comment by pacholoamit** [comment]
Linking this already posted [issue #94 ](https://github.com/mwalbeck/nextcloud-breeze-dark/issues/94) I just checked the console and am seeing this:

![image](https://user-images.githubusercontent.com/69985528/142771492-8820caa4-a250-434d-886a-06d3c06a4ed9.png)

**Comment by mwalbeck** [comment]
The theme not activating is a combination of Chrome and the automated activation option being enabled. When that option is enabled the theme relies on the prefers-color-scheme CSS feature to enable or disable the theme and at least from my testing Chrome isn't that great at necessarily report that correct based on the current desktop theme, at least on Linux. https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

If you just want the theme to be enabled at all times you can just disable that option, and it will stay enable or disabled based on the toggled option in either personal or admin settings.

**Comment by mwalbeck** [comment]
The second issue is pretty much as described in the issue you linked. You can try doing a Ctrl+F5 or running the occ command I referenced in the other issue, as that is most likely just a caching issue.

**Comment by pacholoamit** [comment]
Yeah this is definitely a chrome-related issue... Everything works well on firefox/brave

![image](https://user-images.githubusercontent.com/69985528/142941736-c4b1e3f2-2557-41c6-8b92-72fcdf973765.png)

I've done the `occ maintenance:repair` command. I've also restarted the container as well as cleared redis. Did a `CTRL + F5` and removed application cache in the chromium inspector. No longer see 404s but seeing warning logs

![image](https://user-images.githubusercontent.com/69985528/142942288-80efa321-0e29-4e92-84d0-40403a2bb147.png)

**Comment by mwalbeck** [comment]
Great!

Those warnings are currently expected and not an indication of something being wrong. The shipped version of jQuery in Nextcloud is deprecated and not all core components and apps have been ported to the new system. From what I can see all of those warnings are coming from Nextcloud itself.

**Comment by pacholoamit** [comment]
Closing this issue. Definitely something up with chrome related browsers
