### ISSUE TITLE
The "Start call" icon doesn't appear in Talk

### ISSUE THREAD

**Issue by RoblokazPlays** [mwalbeck/nextcloud-breeze-dark#289]
**Describe the bug**
The icon that's supposed to be in the "Start call" button in Talk is not there.

**To Reproduce**

1. Go to Talk
2. Select a conversation

**Expected behavior**
The icon in the button should have appeared.

**Screenshots**
![image](https://user-images.githubusercontent.com/56515875/143726597-f8e36624-0467-4263-983c-4d145ae0bd51.png)

**Setup (please complete the following information):**

-   Nextcloud version: 22.2.3
-   Theme version: 22.1.0
-   Browser and browser version: Firefox 93.0

**Comment by mwalbeck** [comment]
Thanks for reporting, a fix will be included in the next release!
