### ISSUE TITLE
How do I activate the theme?

### ISSUE THREAD

**Issue by rubo77** [mwalbeck/nextcloud-breeze-dark#29]
I am new to nextcloud, so I thought, I just have to copy the folder into the themes directory.

I did, but the theme is nowwhere visible in my nextcloud settings now.

I only have a setting "Theming" as admin, but there are only some settings for the current theme.

could you please add some more information to the Readme?

**Comment by mwalbeck** [comment]
Hi, have a look at the Installation section of the README [README#Installation](https://github.com/mwalbeck/nextcloud-breeze-dark#installation)

If you have any further questions, let me know.
