### ISSUE TITLE
File selection color is way too bright

### ISSUE THREAD

**Issue by RoblokazPlays** [mwalbeck/nextcloud-breeze-dark#290]
**Describe the bug**
When you select files, the background becomes too bright. It looks strange and it also makes the document icon invisible

**To Reproduce**

1. Select a file or click the share button

**Expected behavior**
I expected the color to be less bright, kind of like the color you get when you hover your mouse over files

**Screenshots**
![image](https://user-images.githubusercontent.com/56515875/144359313-b8204ed6-b3c5-47ec-b70c-faee9ec278d7.png)

**Setup (please complete the following information):**

-   Nextcloud version: 22.2.3
-   Theme version: 22.1.0
-   Browser and browser version: Firefox 94.0

**Additional context**
The display I'm using is slightly brighter than others, but the selection color still looks strange, and it's weird that it makes the document icon invisible.

I tried on other displays too, and while they were less bright, it still looked weird.

**Comment by mwalbeck** [comment]
I do agree that it isn't ideal. I have considered for quite a while now to use the hover colour for the selection colour as well, or a slightly altered version of it.
