### ISSUE TITLE
missing border profile card

### ISSUE THREAD

**Issue by Tealk** [mwalbeck/nextcloud-breeze-dark#291]
**Describe the bug**
/index.php/settings/user missing border on profile card

**To Reproduce**

1. Go to settings
2. Click on Personal Info

**Screenshots**
![light theme](https://user-images.githubusercontent.com/12276250/144755617-6a54afc5-4c1f-4c69-a073-71366f5f2236.png)
![dark theme](https://user-images.githubusercontent.com/12276250/144755620-d7bce421-3cad-486b-a384-89cb1eb14f4c.png)

**Setup (please complete the following information):**

-   Nextcloud version: 23.0.0
-   Theme version: 23.0.0
-   Browser and browser version: FF 94.0.2

**Comment by mwalbeck** [comment]
Thanks for reporting!

I have added a border around the footer portion which has the same colour as the normal background.

![image](https://user-images.githubusercontent.com/19759293/145684078-8baee6c6-879d-4e82-84ea-abbf334fc35d.png)
