### ISSUE TITLE
Support for Templates, different Apple Touch Icons and CSS-Additions …

### ISSUE THREAD

**Issue by Aeneon** [mwalbeck/nextcloud-breeze-dark#292]
I was using the old Version 17.0.1, with a few Customizations and now I was forced to use this terrible App. How can I add custom Touch Icons for Apple Devices ( not only one Resolution for all Devices ) and add Changes to the SCSS-Files ? I don't want to use this preconfigured half-baken Additions, since V18.

Changes I made on the old Version :

- templates/layout.*.php
- img/AppleTouch_57x57.png
- img/AppleTouch_57x57@2x.png
- img/AppleTouch_60x60.png
- img/AppleTouch_60x60@2x.png
- img/AppleTouch_60x60@3x.png
- img/AppleTouch_72x72.png
- img/AppleTouch_72x72@2x.png
- img/AppleTouch_76x76.png
- img/AppleTouch_76x76@2x.png
- img/AppleTouch_83.5x83.5@2x.png
- img/favicon*.*
- img/logo.png
- img/logo@2x.png
- img/logo-icon.png
- img/logo-icon@2x.png

How can I apply these Changes in the App ?

What was the Problem with the old Distribution as Theme ?

**Comment by mwalbeck** [comment]
For changing the favicons I would recommend a hybrid approach where you can have a theme in the theming folder that just consists of the changes you can only make using that feature. You can take a look at the favicons branch, here I have a theme with only favicons included that can be used alongside the app version: https://github.com/mwalbeck/nextcloud-breeze-dark/tree/favicons

Depending on what you're using the templates/layout.*.php files for you can do exactly the same with those.

> and add Changes to the SCSS-Files

For making styling changes I recommend going to the Theming section in the settings, there you will find a custom styling box in the Breeze Dark subsection where you can add your own styling. Though this method only supports CSS not Sass, but you should still be able to make whatever customisations you want, including override the colour variables used in the theme.

> What was the Problem with the old Distribution as Theme ?

The biggest problem is the fact that it got deprecated in Nextcloud 16 and will be removed at some point.
