### ISSUE TITLE
How to enable dark theme

### ISSUE THREAD

**Issue by 807801002** [mwalbeck/nextcloud-breeze-dark#293]
I've enabled app and enabled all the checkbox and saved and refreshed page,but nothing changed at my page theme.
![image](https://user-images.githubusercontent.com/8719537/147864654-17b8e26d-bb41-4e00-8bea-e335c9fd2723.png)
![image](https://user-images.githubusercontent.com/8719537/147864660-2087be55-ba2b-41c7-94aa-2e6e767080eb.png)
![image](https://user-images.githubusercontent.com/8719537/147864708-644014a9-e9f4-4a79-a7e8-297aab3272d7.png)

**Comment by mwalbeck** [comment]
The theme not activating is a combination of your browser and the automated activation option being enabled. When that option is enabled the theme relies on the prefers-color-scheme CSS feature to enable or disable the theme. https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

When using the option your browser would report your preference based on the theme you use for your browser. If you're using Chrome then it doesn't really seem to work at the moment, but Firefox does work as intended.

If you just want the theme to be enabled at all times you can just disable that option, and it will stay enable or disabled based on the toggled option in either personal or admin settings.
