### ISSUE TITLE
Nextcloud Office

### ISSUE THREAD

**Issue by drikqlis** [mwalbeck/nextcloud-breeze-dark#296]
Now that Collabora is integral part of the Nextcloud suite and got new look to match default Nextcloud theme it would be great to also integrate it with this theme if it is possible. For now the new theme of Collabora looks out of place with breeze-dark, and some things are not displayed properly (background of items, hovering on tabs etc.).

**Comment by mwalbeck** [comment]
Hi! I've been looking to style Collabora for a long time, but it hasn't really been possible yet as the theming support needed wasn't there. Now, I know they have been working on it to support dark themes for Collabora, so when the final support lands I'll be adding proper support for it.

I'll see if I can't iron out some of the styling issue in the meantime.

**Comment by mwalbeck** [comment]
There wasn't much I could do until proper theming support lands, but I've at least fixed the text colour on the loading screen

https://github.com/mwalbeck/nextcloud-breeze-dark/pull/305
