### ISSUE TITLE
Autoswitch

### ISSUE THREAD

**Issue by rightsaidfred99** [mwalbeck/nextcloud-breeze-dark#297]
**What feature would you like to see added to the theme?**:
Currently only theme/app supports dark mode. 
Would it be possible to add in a switch to read system prefs for system wide dark mode / system wide dark mode. 

So if a user had it on, Breeze enabled. Off, just default Nextcloud theme. 

**Your setup (please complete the following information):**
Currently most websites support this, even GitHub. 

-   Nextcloud version: [e.g. 17.0.3]
23x

**Comment by mwalbeck** [comment]
This is actually already implemented. If you go into the settings and enable the Breeze Dark automated activation then the theme relies on the [prefer-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) media query to enable or disable the theme. Though at the moment support for the feature isn't created equally. People have reported it not really working at all with Chrome, but working fine in Firefox. So keep that in mind.
