### ISSUE TITLE
Agenda current day color is too bright

### ISSUE THREAD

**Issue by mmallejac** [mwalbeck/nextcloud-breeze-dark#298]
**Describe the bug**
Within the agenda, the current day color is too bight.

**Expected behavior**
I would expect a lighter color, as when using the default theme (light blue on white)

**Screenshots**

Without Breeze Dark:
![image](https://user-images.githubusercontent.com/11666281/157202337-574cf3a2-47d1-4d7b-a5ff-affed036c259.png)

With Breeze Dark:
![image](https://user-images.githubusercontent.com/11666281/157202656-ff0d1cf3-04a2-4795-b2a6-098b7cb70283.png)

**Setup (please complete the following information):**
-   Nextcloud version: 22.2.5
-   Theme version: 22.3.0
-   Browser and browser version: Firefox 97.0.2

**Comment by mwalbeck** [comment]
Hi,

I very much agree, and I have actually already fixed this, I just haven't pushed a release for Nextcloud 22 yet with the changes. I'll do that shortly, so you should see the new updates in Nextcloud within a few hours.
