### ISSUE TITLE
Menu header-right invisible

### ISSUE THREAD

**Issue by nagodoy** [mwalbeck/nextcloud-breeze-dark#30]
Invisible menu
Active and inactive options are not visible in the User Setup Menu

https://www.dropbox.com/s/lz4s6ww775nx5o1/Captura%20de%20Tela%202018-08-25%20%C3%A0s%2009.58.32.png?dl=0

**Comment by mwalbeck** [comment]
Hi, sorry for the slow response.

Could you tell me the following about your setup.

Nextcloud version
Theme version
Browser and browser version

Thanks

**Comment by nagodoy** [comment]
Hi
No problem.
OS: High Sierra and Windows 7
Browser: Chrome Version 68.0.3440.106
Nextcloud: 13.0.5
Theme version: A Breeze Dark theme for Nextcloud: https://github.com/mwalbeck/nextcloud-breeze-dark <https://github.com/mwalbeck/nextcloud-breeze-dark>

Thanks
Nelson

**Comment by mwalbeck** [comment]
Hi

I can only reproduce your problem if I switch to a version of my theme made for Nextcloud 12. If you could make sure that you are using the latest version of the theme, that would be great. If not, then try and update to the latest version and see if that doesn't fix the problem.

You can find the version number in the theme folder under **core/css/server.css** The version number should be at the top of the server.css file.

**Comment by mwalbeck** [comment]
As there haven't been any updates on this issue, I'm gonna assume it has been resolved.
