### ISSUE TITLE
Deck: Marked text of a card description is white on white

### ISSUE THREAD

**Issue by tigexplorer** [mwalbeck/nextcloud-breeze-dark#301]
**Describe the bug**
Marked text of a card description is white on white

**To Reproduce**

1. View details of a card
2. Mark the text in the description box
3. The white text is marked white

**Expected behavior**
The text should marked grey or other different of white

**Screenshots**
![Auswahl_011](https://user-images.githubusercontent.com/43775552/161133003-0ffd4228-7499-48a7-8179-24666d532c78.png)

**Setup (please complete the following information):**

-   Nextcloud version: 22.2.5
-   Theme version: 22.3.1
-   Browser and browser version: Firefox 98.2

**Comment by mwalbeck** [comment]
Hi, from the screenshots it looks like you're using the official dark theme and not the breeze dark theme.

![image](https://user-images.githubusercontent.com/19759293/161644564-5702c35f-49e2-4b70-8cfd-b4fa74ea7113.png)

**Comment by tigexplorer** [comment]
Ah, yes, thanx for the hint!

**Comment by danir-de** [comment]
#close ?
