### ISSUE TITLE
Compatibilty to Nextcloud 24

### ISSUE THREAD

**Issue by 42ske** [mwalbeck/nextcloud-breeze-dark#303]
Do you already know, when we will see a version compatible to Nextcloud 24? Thanks in advance.

**Comment by cyberjohn57** [comment]
I just installed NC24 RC3 on an Ubuntu 22.04 server and enabled the Breeze Dark theme and appears to be running fine with no issues noted so far.

**Comment by mwalbeck** [comment]
Thanks for testing it @cyberjohn57 I have extremely limited time at the moment, but I'll probably push out an initial release for NC24 so upgrading is easy and the only issues there should be present are minor styling issues. If anyone finds any of those issues please do report them, It's going to be a big help!

**Comment by mwalbeck** [comment]
I had a look through Nextcloud 24 with the theme enabled and couldn't find any issues preventing the release, so I have just pushed out a release for Nextcloud 24.

**Comment by cyberjohn57** [comment]
Glad to help.  Excellent program as I use it on all my Nextcloud installs.
