### ISSUE TITLE
Talk App Reaction Buttons

### ISSUE THREAD

**Issue by danir-de** [mwalbeck/nextcloud-breeze-dark#304]
**Describe the bug**
The reaction buttons in the new Talk 14 have a bright background that really conflicts with the text color.
![image](https://user-images.githubusercontent.com/4672840/167103584-34df6073-1b46-4775-9fb8-9c103bad0575.png)

**To Reproduce**

1. Go to 'Talk'
2. Click on 'Any Chat'
3. React via Emoji 
4. Let others react via Emojis
5. See error

**Expected behavior**
Readable Emoji buttons.

**Setup:**

-   Nextcloud version: 24.0.0
-   Theme version: 24.0.0
-   Browser and browser version: Chrome 101

**Comment by mwalbeck** [comment]
Thanks for reporting, it's fixed in the latest release!
