### ISSUE TITLE
BREEZE DARK + COSPEND = can’t read selected project name

### ISSUE THREAD

**Issue by punkyard** [mwalbeck/nextcloud-breeze-dark#307]
Nextcloud 24.0.3
Operating system and version Ubuntu 20.04
PHP version 7.4

The issue you are facing:
can’t read project name in cospend when using BREEZE DARK theme
covered in blue
plus, the name of the project is shortened and doesn’t display fully, as expected: (2022 10 lataa…)

![Capture d’écran 2022-07-21 à 11 32 43](https://user-images.githubusercontent.com/59349105/180192243-881115b4-b6ea-4a47-b1d0-4155fb9f29be.png)

**Comment by sunjam** [comment]
[See related discussion on the forum](https://help.nextcloud.com/t/breeze-dark-cospend-cant-read-selected-project-name/142525/4) in case you'd like to talk about this there.

Cheers, and thanks for the awesome theme.  :heart:

**Comment by mwalbeck** [comment]
Thanks for reporting! There should be a fix in 24.0.2, which is out now!
