### ISSUE TITLE
Music Icons are Black instead of Grey

### ISSUE THREAD

**Issue by JoshuaPettus** [mwalbeck/nextcloud-breeze-dark#308]
**Describe the bug**
Most of the icons on music's left panel are black instead of grey.  I see this is suppose to be a stylized and supported app

**To Reproduce**
Open up the music.  The left bar icons are black except "New Playlist"

**Screenshots**
If needed I'll see if I can make one

**Setup (please complete the following information):**

-   NC 24
-   Theme version: 24.0.2
-   Firefox 102

**Comment by mwalbeck** [comment]
Thanks for reporting! I don't use the music app myself, and I sadly don't have time to test all the apps, so I very much appreciate the bug report!

**Comment by JoshuaPettus** [comment]
Of course!

**Comment by mwalbeck** [comment]
Thanks again for reporting! The fix will be included in the next release!
