### ISSUE TITLE
tick button disappears in Polls

### ISSUE THREAD

**Issue by punkyard** [mwalbeck/nextcloud-breeze-dark#309]
![Capture d’écran 2022-08-19 à 01 10 09](https://user-images.githubusercontent.com/59349105/185633830-29970f95-d85c-4eed-8444-0bc23255030d.png)

![Capture d’écran 2022-08-19 à 01 10 01](https://user-images.githubusercontent.com/59349105/185633851-8cc159df-1c65-442a-a285-068a1432f8f4.png)

**Comment by mwalbeck** [comment]
Thanks for reporting! The fix will be included in the next release!
