### ISSUE TITLE
White background of the music player in the music app when playing any track

### ISSUE THREAD

**Issue by Kitanit** [mwalbeck/nextcloud-breeze-dark#310]
Music app https://apps.nextcloud.com/apps/music 1.6.0
Breeze Dark 24.0.2
Nextcloud 24.0.3
Brave linux [Версия 1.42.97 Chromium: 104.0.5112.102
![image](https://user-images.githubusercontent.com/65107731/185668071-23c03d48-f287-44de-8461-81e1cf48dc7e.png)

**Comment by mwalbeck** [comment]
Thanks for reporting! The fix will be included in the next release!
