### ISSUE TITLE
Mail app displays white background on email content

### ISSUE THREAD

**Issue by NablaMetal** [mwalbeck/nextcloud-breeze-dark#314]
When browsing Nextcloud with Breeze Dark theme enabled, everything looked like it should except on the default mail app, the mail content are most of the time displayed with a white background :
![image](https://user-images.githubusercontent.com/21262052/188613381-f9284901-6d80-445e-8d50-f6fcd49f7f60.png)

Some mails happen to be displayed correctly with gray background.

-   Nextcloud version: 24.04 Docker latest official image - Ubuntu 22.04 host.
-   Theme version: 24.02
-   Mail app version: 1.13.8
-   Browser and browser version:
     -   Brave Browser Version 1.43.89 Chromium: 105.0.5195.102,
     -   Edge Version 105.0.1343.27
     -   Firefox 104.0.1
Regards,

**Comment by mwalbeck** [comment]
Hi,

This is intended behaviour at the moment. It depends on the type of email. Plain text emails are display directly and are therefore styled with a dark background and light text. HTML emails on the other hand is display in an iframe, which makes it quite difficult to style. That combined with all the various compatibility issues that might appear with styling HTML emails from all manner of sources means I've decided to just stick to a light theme for that one part.

**Comment by NablaMetal** [comment]
OK, I understand. Thank you.
