### ISSUE TITLE
no login image background after fresh install

### ISSUE THREAD

**Issue by punkyard** [mwalbeck/nextcloud-breeze-dark#318]
**Describe the bug**
after a fresh install of NC 24 05 on ubuntu 22.04
after activation of theming and dark breeze + options as Theme the login page
there is no background at login

**Expected behavior**
blue icons on grey background

**Screenshots**
![Capture d’écran 2022-09-30 à 19 02 17](https://user-images.githubusercontent.com/59349105/193321743-2ad8bc79-62fd-45cb-8e4c-cd0a6dc8675f.png)

**Setup (please complete the following information):**
NC 24 05
-   Theme version: 24 02
-   Browser and browser version: brave / safari

**Comment by mwalbeck** [comment]
Hi, in the theming app settings, what is the "Login image" option set to?

**Comment by punkyard** [comment]
nothing is set there.
As the background was not displayed, i've uploaded a picture and then deleted it to see if the default background would come back, but no.

**Comment by mwalbeck** [comment]
If there is no background image there should be a button to restore the default background image

![image](https://user-images.githubusercontent.com/19759293/193947355-89a8995c-c2c8-44ba-affc-72537ec651bf.png)

**Comment by punkyard** [comment]
simple and efficient
I didn't think about doing this! Thanks

It's the first time this grey background appeared, right after the install..

cheers !

Le 5 oct. 2022 à 01:13, Magnus Walbeck ***@***.***> a écrit :


If there is no background image there should be a button to restore the default background image

 <https://user-images.githubusercontent.com/19759293/193947355-89a8995c-c2c8-44ba-affc-72537ec651bf.png>
