### ISSUE TITLE
Breeze Dark Theme Affects Nextcloud Tasks Layout

### ISSUE THREAD

**Issue by BrandonMFong** [mwalbeck/nextcloud-breeze-dark#321]
Is it okay if I just refer to this bug issue? https://github.com/nextcloud/tasks/issues/2140

A developer from that team noticed it was due to Breeze Dark Theme. Let me know if I must provide more information for you.

**Comment by mwalbeck** [comment]
Thanks for reporting, I've added a fix that will be in the next release!
