### ISSUE TITLE
How can I change --color-main-background to rgba(17, 17, 17, 1) ?

### ISSUE THREAD

**Issue by DalekDave** [mwalbeck/nextcloud-breeze-dark#323]
I want to change the main background color from --color-charcoal-gray to rgba(17, 17, 17, 1)

Please could you explain the steps I will need to follow  do that?

Thank you for your work on Breeze Dark! :)

**Comment by DalekDave** [comment]
The solution is to open /var/www/nextcloud/apps/breezedark/css/guest.css and edit line 43 to:

`    --color-main-background: rgba(17,17,17,1) !important;
`
No recompiling or other action was necessary. It's not the cleanest way to do it, because the change will get written over in the next update to BreezeDark, but it works for me.

**Comment by mwalbeck** [comment]
A better approach would be to add the following to the Custom Styling box in the theming settings in Nextcloud. I added that option to make this kind of modification more accessible

```
:root {
    --color-main-background: rgba(17,17,17,1) !important;
}
```
