### ISSUE TITLE
Markdown editor styling

### ISSUE THREAD

**Issue by ail1020** [mwalbeck/nextcloud-breeze-dark#33]
The preview pane in the [markdown editor](https://apps.nextcloud.com/apps/files_markdown) shows a white background, messing with the preview since the text ends up being white as well.

**Comment by mwalbeck** [comment]
Hi,

Thanks for reporting

Had a bit of time to do a few things, so this should now be fixed in the latest release.

**Comment by ail1020** [comment]
Thanks for such a quick response, it's much better now. After some playing around and testing, the only thing I noticed still being off is the color of the text in a code block.
If you do something like this, the text in the code block is still a dark color and almost impossible to see.
```
uptime -p
```
