### ISSUE TITLE
Clean uninstall of the app is impossible and breaks nc light theme

### ISSUE THREAD

**Issue by HannesJo0139** [mwalbeck/nextcloud-breeze-dark#330]
With NC25 I decided to disable and uninstall breeze dark. Leading to the the following issue
https://github.com/nextcloud/server/issues/36860

**Comment by mwalbeck** [comment]
If you reinstall the app, then disable the theme in the Appearance and accessibility settings and then uninstall the app, then it should be back to normal.

To properly fix this, I'll look into implementing some clean-up logic, so this happens automatically when you uninstall.

**Comment by mwalbeck** [comment]
Thanks again for reporting this! A fix will be in the next release
