### ISSUE TITLE
Styling request for SnappyMail (black background in input fields)

### ISSUE THREAD

**Issue by thecpcat** [mwalbeck/nextcloud-breeze-dark#333]
Hi. Is it possible to lighten the black background in input and search fields? See the screenshots.
BreezeDark in selected as a server-wide default theme.

**Which app would you like to have styled**:
SnappyMail 	2.27.3 (latest)
BreezeDark 	25.0.2 (latest)	

**Your setup (please complete the following information):**

-   Nextcloud version: Nextcloud Hub 4 (26.0.0) (latest)

<img width="556" alt="image" src="https://user-images.githubusercontent.com/24196232/230716396-f2b437e8-bcf1-4976-a701-d5ccbc5ffe4f.png">

<img width="556" alt="image" src="https://user-images.githubusercontent.com/24196232/230716204-ae1392e6-7605-41f0-b1a7-bb0f9f970cca.png">

**Comment by mwalbeck** [comment]
Should be fixed in the just released v26.0.0
