### ISSUE TITLE
Toolbar in text app: Icon of button of the applied text style invisible

### ISSUE THREAD

**Issue by MarcelvC** [mwalbeck/nextcloud-breeze-dark#336]
**Describe the bug**
In the text editor, when the cursor is placed over styled text (bold, H1, etc.), the background of the toolbar button representing the applied text style is highlighted, but the icon is not visible.

**Steps to reproduce the behavior:**

1. Open Text app
2. Enter text into the editor
3. Apply a style to the text (bold, H1 etc.)
4. Place the cursor over the styled text
5. In the toolbar, the background of the button corresponding to the applied text style is highlighted, but the icon is not visible

**Screenshots**
![Screenshot Text app](https://github.com/mwalbeck/nextcloud-breeze-dark/assets/12641226/f4408a70-fc10-44e8-a643-6bc187693a3a)

**Setup:**

-   Nextcloud version: 26.02
-   Theme version: 26.0.0
-   Browser and browser version: Firefox 114.0.1

**Comment by mwalbeck** [comment]
Thanks for reporting, it will be fixed in the next version which will be out shortly
