### ISSUE TITLE
Update to NC28 please

### ISSUE THREAD

**Issue by Lila-Kuh** [mwalbeck/nextcloud-breeze-dark#339]
Could you update this app to be compatible with NC28?
Thanks

**Comment by IgorA100** [comment]
There are probably no people willing to adapt to version 28, and there have been no commits for a year now :(

**Comment by LukaPitamic** [comment]
pretty please...
![599536](https://github.com/mwalbeck/nextcloud-breeze-dark/assets/34914144/73b931d1-ec0d-4179-b51d-9a9819a72e5a)
