### ISSUE TITLE
Theme fail

### ISSUE THREAD

**Issue by florealcab** [mwalbeck/nextcloud-breeze-dark#34]
For me the theme juste does not works...

When I activate it I have this error replacing the logo in the top bar:
Error: File to import not found or unreadable: apps/base/notifications.\A on line 27 of server.scss\A \A 22: @import 'apps/base/first-run-wizard';\A 23: @import 'apps/base/gallery';\A 24: @import 'apps/base/log-reader';\A 25: @import 'apps/base/news';\A 26: @import 'apps/base/notes';\A 27: @import 'apps/base/notifications';\A 28: @import 'apps/base/text-editor';\A 29: @import 'apps/base/two-factor';\A 30: // Extra\A 31: \A 32: @import 'apps/extra/audio-player';

And the theme is the default one.

How to fix it?

**Comment by mwalbeck** [comment]
Hi,

This was an issue with the 14.0.0 release and should've been fixed with 14.0.1. I recommend you try and update the theme to the latest version and see if that doesn't fix it.

**Comment by florealcab** [comment]
I have the 14.0.2 version. I tried before with the 14.0.1 version, same issue...
I have the latest version of the theme (git pull says me "already up to date".

**Comment by florealcab** [comment]
Hmm.. cache problem, I do ctrl+shift+r and the theme now works, thank you!

**Comment by mwalbeck** [comment]
Great to hear, hope you enjoy the theme.
