### ISSUE TITLE
Error "Enforced theme not found" while it works correctly

### ISSUE THREAD

**Issue by oscarcp** [mwalbeck/nextcloud-breeze-dark#344]
**Describe the bug**
I have installed Breeze Dark (for NC 28) on an NC 29.0.4 instance successfully. The theme is correctly applied and I have set it as enforced globally for all users. Despite the theme being applied and obviously existing, I get every few minutes the error "enforced theme not found".

**To Reproduce**

1. Install Breeze Dark on an NC 29.0.4 instance
2. Activate enforcing the theme globally
3. See error in logs

**Expected behavior**
No errors should be shown.

**Screenshots**
![Screenshot from 2024-07-28 09-52-33](https://github.com/user-attachments/assets/e7e8c737-8455-4900-ad90-a23000038f23)

![Screenshot from 2024-07-28 09-44-48](https://github.com/user-attachments/assets/45de23f8-cad7-4401-8539-b8b9e6a703bb)
![Screenshot from 2024-07-28 09-50-53](https://github.com/user-attachments/assets/9191321d-4fd6-47ba-85be-d26adcfad363)

**Setup (please complete the following information):**

-   Nextcloud version: 29.0.4 (AIO version)
-   Theme version: 28.0.0
-   Browser and browser version: LibreWolf 128.0-2

**Comment by mwalbeck** [comment]
Thanks for reporting!

I can see there was a recent change to the theming app, that made it so the current way I was doing part of the theme injection caused this. I've changed the implementation, so this should be fixed in the next release.
