### ISSUE TITLE
very white offline client after installing breeze dark in web

### ISSUE THREAD

**Issue by NikoQT** [mwalbeck/nextcloud-breeze-dark#348]
**Describe the bug**
After installing breeze dark my desktop client is now very white with white background AND white text. I didn't enable the client theme enforcement online so what is the problem?

**Comment by mwalbeck** [comment]
This is a bug with the Nextcloud desktop client, it has already been reported and they are working on a fix. The theme has no effect on the desktop client, only the webinterface.
