### ISSUE TITLE
Uncaught Error: Call to a member function getLoggerUncaught Error: Call to a member function getLogger

### ISSUE THREAD

**Issue by karloluiten** [mwalbeck/nextcloud-breeze-dark#38]
Hi all! Screenshots of nextcloud-breeze-dark look good. So I'd like to try it.
I gloned the repo in my themes folder, and made the config change. I also chowned the files for user apache, and restored the cselinux context.

In my logs I get:

`Uncaught Error: Call to a member function getLoggerUncaught Error: Call to a member function getLogger`
To be more specific:

`[Wed Oct 31 20:04:07.814732 2018] [:error] [pid 26938] [client 10.0.60.16:57024] PHP Parse error:  syntax error, unexpected ''nextcloud-breeze-dark'' (T_CONSTANT_ENCAPSED_STRING), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /var/www/html/config/config.php on line 38`

Am I doing something wrong? Thanks!

**Comment by mwalbeck** [comment]
Hi,

It seems to be a problem in your config.php, could you post the contents of it? Remember to remove any sensitive information.

**Comment by karloluiten** [comment]
> Hi,
> 
> It seems to be a problem in your config.php, could you post the contents of it? Remember to remove any sensitive information.

Thanks for your suggestion. I typed `->` instead of `=>`. Changing that fixed it.
