### ISSUE TITLE
Source map error

### ISSUE THREAD

**Issue by Alexey-Akishin** [mwalbeck/nextcloud-breeze-dark#40]
In Firefox in its Console I get the following error:
```
Source map error: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://test-domain/themes/breeze-dark/core/css/server.css?v=a9f9ecf4-6
Source Map URL: server.css.map
```
I'm not sure what it means. Is this an issue with my configuration or is an issue with the theme? I have latest origin/master version installed.

**Comment by mwalbeck** [comment]
Hi, this is currently a "problem" with the theme. The source map is a file that helps with debugging CSS problems and doesn't affect the theme in any way. I currently doesn't include the source map as it has cause merge conflicts in the past. So it isn't something to worry about.
