### ISSUE TITLE
location on snap install

### ISSUE THREAD

**Issue by ghost** [mwalbeck/nextcloud-breeze-dark#41]
git cloned into `/var/snap/nextcloud/current/nextcloud/themes/nextcloud-breeze-dark` and added to config/config.php but no theme change

the settings page says that I've set a custom setting so it seems like the theming folder is just wrong or something?

vanilla nc 14

thanks

**Comment by mwalbeck** [comment]
Hi, last I looked into it, using a custom theme with the Nextcloud snap wasn't possible. I don't really know the specifics, but you can try and ask over on the github page for the nextcloud snap.

**Comment by mwalbeck** [comment]
Added entry in README
