### ISSUE TITLE
nextcloud 15 bugs

### ISSUE THREAD

**Issue by Aviorleking** [mwalbeck/nextcloud-breeze-dark#43]
I tried your theme on nextcloud 15 (branch 15) and i report these to you ;)

---

icons on explorer aren't showing in grid mode (they only appear on hover)
![image](https://user-images.githubusercontent.com/15822031/49740977-b4e47d80-fc95-11e8-8897-a07b9159bbe8.png)

---

I don't know if you can edit them but Apporder app icons are black
![image](https://user-images.githubusercontent.com/15822031/49741170-1ad10500-fc96-11e8-8c80-768441d33ad2.png)

and dashboard icons too (there is also the button on the bottom right part)
![image](https://user-images.githubusercontent.com/15822031/49741219-389e6a00-fc96-11e8-9904-f43307840373.png)
(the dock isn't part of the cloud)

---

the help documention has the text in black
![image](https://user-images.githubusercontent.com/15822031/49741599-11946800-fc97-11e8-90ee-deb8697cddab.png)

---

Everything else is perfect !

**Comment by mwalbeck** [comment]
Thanks a bunch. I'll take a closer look at it and have it fixed for the first release. Let me know if you notice anything else.

**Comment by Aviorleking** [comment]
I won't hesitate :wink:

**Comment by mwalbeck** [comment]
The new release is out. I fix the above things except for the documentation because the text is in an iframe so I have no control over the styling.

**Comment by Aviorleking** [comment]
ok thanks :)

**Comment by rcdailey** [comment]
I'm still seeing a white bar:

![image](https://user-images.githubusercontent.com/1768054/49812396-f70bce80-fd2a-11e8-8302-0d1899c139bf.png)

**Comment by Aviorleking** [comment]
Have you updated.to the latest ?

**Comment by rcdailey** [comment]
Yes, I am on latest in `master`.

**Comment by rcdailey** [comment]
There's also a styling issue with the new text that appears for menu items when you hover over them. There is a box around the text. I believe the box should not be there.

![image](https://user-images.githubusercontent.com/1768054/49813728-b1043a00-fd2d-11e8-8dc3-c665ee6b384c.png)

**Comment by Aviorleking** [comment]
Youre not its been corrected in the latest one 😃(i use it)

**Comment by Aviorleking** [comment]
I just checked back (deleting the theme files and putting the latest commit [this one](https://github.com/mwalbeck/nextcloud-breeze-dark/commit/c1716a8da67c2bfc3de0838a3f82fa945c0cd961) and the theme work just fine without the bugs I mentioned earlier.

**Comment by rcdailey** [comment]
Sorry, spoke too soon: Did a CTRL+F5 to refresh browser cache and now it works.

So: If anyone else hits this issue, delete your browser cache!!
