### ISSUE TITLE
some problems

### ISSUE THREAD

**Issue by Aviorleking** [mwalbeck/nextcloud-breeze-dark#44]
hidden file (files starting with a dot) aren't showing their name
![image](https://user-images.githubusercontent.com/15822031/49800160-1c0e3a80-fd47-11e8-86c5-1342db9337e4.png)
the file is named .Contacts-Backup and the name should be visible.
(using latest at master)

---

also 
the bookmark icon is black in the settings
![image](https://user-images.githubusercontent.com/15822031/49822911-ae7e0080-fd7e-11e8-8912-e3072ce96767.png)

**Comment by mwalbeck** [comment]
Thank you for the assistance. It's now fixed and will be included in the next release.

**Comment by Aviorleking** [comment]
ok ;)
