### ISSUE TITLE
files_markdown: add styling for syntax highlighting

### ISSUE THREAD

**Issue by Aviorleking** [mwalbeck/nextcloud-breeze-dark#45]
Below is a is snippet but its not coloring nor the text in itself.
![image](https://user-images.githubusercontent.com/15822031/49868026-76250380-fe0c-11e8-9bb4-08c6b43e5aa6.png)

**Comment by Aviorleking** [comment]
it's this one https://apps.nextcloud.com/apps/files_markdown

**Comment by mwalbeck** [comment]
Okay thanks, I'll take a look.

**Comment by mwalbeck** [comment]
Okay, so I've had a quick look and I need to add CSS for the syntax highlighting. It would be a great help if you could post some code snippets where you notice styling problems, then I can quicker add some syntax highlighting that works with this theme.

**Comment by Aviorleking** [comment]
there are pre-done highlighters already available like this one: https://github.com/highlightjs/highlight.js/blob/master/src/styles/a11y-dark.css

and many more here: https://highlightjs.org/static/demo/

but if you want code snippets a copied the ones on the link above but here is it :
https://cloud.delta-wings.net/index.php/s/TKXww69aQLr6T72

**Comment by mwalbeck** [comment]
Oh okay, great. Thank you for the links, it should be a lot easier than I first expected.

**Comment by Aviorleking** [comment]
Your welcome :smile:

**Comment by mwalbeck** [comment]
Okay, I've decided to include the highlighting theme you recommended. I might look at making a highlighting theme based on the Breeze Dark highlighting theme but for now there are other things for this theme I would rather work on. Syntax highlighting is hard to get right.

**Comment by Aviorleking** [comment]
OK thanks for your work :blush:
