### ISSUE TITLE
Markdown Table

### ISSUE THREAD

**Issue by Aviorleking** [mwalbeck/nextcloud-breeze-dark#47]
In the [markdown editor](https://apps.nextcloud.com/apps/files_markdown) there is a problem with tables showing this 
![image](https://user-images.githubusercontent.com/15822031/50398059-fb95a580-0774-11e9-8451-ae0d8b75eb45.png)
the source code is below
```
| Companie | type | capcité |
| -------- | ---- | ------- |
| WD | PC | 120 GB |
```

**Comment by mwalbeck** [comment]
Fixed, thanks.
