### ISSUE TITLE
Extend theme to JavaScript XMPP Chat

### ISSUE THREAD

**Issue by 0E800** [mwalbeck/nextcloud-breeze-dark#48]
Thank you for this excellent theme. I appreciate the time you took to make it and even more so that you shared it here.

Any chance you can theme the JavaScript XMPP Chat panel?

**Comment by mwalbeck** [comment]
Thanks for enjoying the theme.

Yeah, I'll have a look at it.

**Comment by mwalbeck** [comment]
Added in the latest release, let me know if notice any issues.
