### ISSUE TITLE
Bug for passman

### ISSUE THREAD

**Issue by florealcab** [mwalbeck/nextcloud-breeze-dark#49]
The top bar of passman disappeared with this theme. So we can't add new passwords anymore.

As you can see, the top bar is blank now:

![image](https://user-images.githubusercontent.com/16965090/51426778-ade35000-1bef-11e9-8bdd-3b1a2128331e.png)

**Comment by mwalbeck** [comment]
Thanks for reporting, I'll get it fixed for the next release, which will be no later than Wednesday.

**Comment by mwalbeck** [comment]
As this might be quite annoying here is a quick fix you can add to the bottom of your server.css file, as I plan to do an overhaul of the styling for Passman before the next release.

```
.app-passman #app-content #app-content-wrapper #passman-controls {
	top: unset;
}
```

**Comment by florealcab** [comment]
Thank you a lot, it works :D

Le 19/01/2019 à 15:35, Magnus Walbeck a écrit :
> |.app-passman #app-content #app-content-wrapper #passman-controls { 
> top: unset; }|

**Comment by florealcab** [comment]
Thank you a lot, it works! Thank you for this very quick fix :)

**Comment by mwalbeck** [comment]
Fixed in latest release
