### ISSUE TITLE
dark folder icons with theming app

### ISSUE THREAD

**Issue by fjepsen** [mwalbeck/nextcloud-breeze-dark#50]
I set up a new nextcloud server 15.0.4/now15.0.5 using theming app to change name, slogan, color, logos and favicon.

with activated theming app I now have dark folder icons:
 ![grafik](https://user-images.githubusercontent.com/48312298/53941769-46a72f80-40b9-11e9-8621-3a7bcc23cb78.png)
`<div class="thumbnail" style="background-image: url("/index.php/apps/theming/img/core/filetypes/folder-shared.svg?v=20");"><div class="favorite-mark ">`

with deactivated theming app folder icons are ok but only standard logos etc.:
![grafik](https://user-images.githubusercontent.com/48312298/53941570-b537bd80-40b8-11e9-8226-2d9d22eaca42.png)
`<div class="thumbnail" style="background-image: url("/core/img/filetypes/folder-shared.svg");"><div class="favorite-mark ">`

**Comment by fjepsen** [comment]
Now I found a solution.
With default color in Theming it works:
![grafik](https://user-images.githubusercontent.com/48312298/53954382-5ed97780-40d6-11e9-9478-50c4c9dd0b34.png)
And thanks to nextcloud-breeze-dark theme logon screen and the rest still stays dark.

Sorry for opening an issue unnecessarily.

**Comment by mwalbeck** [comment]
Yeah, I'm not replacing the folder icons in the theme as I didn't see the need for it, so they are affect by the color attribute in the theming app.

No worries, let me know if you have any other problems.
