### ISSUE TITLE
dark icons

### ISSUE THREAD

**Issue by Aviorleking** [mwalbeck/nextcloud-breeze-dark#51]
some icons aren't white :p
![image](https://user-images.githubusercontent.com/15822031/54351527-f4818380-464f-11e9-9ac1-09cf576a9740.png)
![image](https://user-images.githubusercontent.com/15822031/54351575-10852500-4650-11e9-9340-9ae9dd97e429.png)

**Comment by mwalbeck** [comment]
This problem seems to be the same as #31 which I don't have a concrete solution for. You can try running the occ command **maintenance:theme:update**

**Comment by HydrexHD** [comment]
![photo5249160857550695007](https://user-images.githubusercontent.com/17232346/55079028-adf24700-509b-11e9-85d8-1f657fab8035.jpg)

I have this Problem on my Nextcloud 15. I tried **occ maintenance:theme:update**

**Comment by mwalbeck** [comment]
It might be your browser cache, you can try clearing it or do a CTRL+F5. If it doesn't work please open up a new issue instead of replying on this one as they are 2 different problems.

**Comment by mwalbeck** [comment]
I'm going to close this issue as there haven't been any further updates and it is similar to #31
