### ISSUE TITLE
Bookmarks App: Fix popovermenu in list view

### ISSUE THREAD

**Issue by tossican** [mwalbeck/nextcloud-breeze-dark#52]
Thank you for your great theme! ..  

There is however an issue with the bookmarks app. The issue was not yours alone, it exists with the core theme as well. However, the author is now fixing it.. I have manually added his fix and it works great with the core theme, but I have no clue where/how to add it in your code.

Original report: https://github.com/nextcloud/bookmarks/issues/662
The fix: https://github.com/nextcloud/bookmarks/commit/485b30b224adc888fcc21405ff4d8e5fdb1237f1

I hope this helps.

**Comment by mwalbeck** [comment]
Hi, thanks for letting me know. From what I can see these changes will automatically work with this theme, as I'm not overwriting that styling in any way. Though I do think the Bookmarks theming could be a bit better so I'll give it a small overhaul.

**Comment by mwalbeck** [comment]
Improved styling in the newest release
