### ISSUE TITLE
Problems with Nextcloud 15

### ISSUE THREAD

**Issue by HydrexHD** [mwalbeck/nextcloud-breeze-dark#53]
![55079028-adf24700-509b-11e9-85d8-1f657fab8035](https://user-images.githubusercontent.com/17232346/55141458-b8afe900-513a-11e9-95ac-a4ddd685a46e.jpg)

I have this Problem on my Nextcloud 15. I tried **occ maintenance:theme:update** and also clearing the Browser cache **(ctrl + F5)**

**Comment by mwalbeck** [comment]
Thanks for reporting back.

If you know how, could you open the HTML inspection tool and see if the CSS is being overwritten by something or if it is never applied. 

I'm inclined to believe it's the former as some styling from the theme is applied. It might be a browser plugin that's the culprit. Let me know what you find.

**Comment by HydrexHD** [comment]
I have open the HTML inspector tool. Is therer anything you need to find the error?
![image](https://user-images.githubusercontent.com/17232346/55151468-a0e26000-514e-11e9-8263-704f7447a5aa.png)

**Comment by HydrexHD** [comment]
![NC](https://user-images.githubusercontent.com/17232346/55151722-28c86a00-514f-11e9-999e-0090169c2e10.jpg)
I have open the HTML inspection tool. Is there anything you need to find the error?

**Comment by mwalbeck** [comment]
Great, if you look at the id selector #controls and its background-color value. It's set to a variable, all the variable definitions are at the bottom so if you scroll all the way down and find the instance of --color-main-background-translucent that isn't crossed over and send me a screenshot of that. I've added a screenshot that hopefully helps a bit. 
![image](https://user-images.githubusercontent.com/19759293/55160755-01998900-519f-11e9-9e41-5090b3274b52.png)

Secondly, I can from your screenshot that it seems the Custom CSS plugin is in use, is that correct? If so could you try to disable it and see if that changes anything

**Comment by rcdailey** [comment]
I wanted to pitch in and say I'm seeing this exact same issue on Nextcloud 16 Beta. I do have the Custom CSS plugin enabled, but I actually use it:

```css
#header .header-shared-by {
  display: none;
}

#body-public footer {
  display: none;
}
```

I use this CSS to hide some of the stuff you see on the page for public file share links. I do not want to disable this.

**Comment by rcdailey** [comment]
Also: Disabling Custom CSS didn't change anything for me

**Comment by rcdailey** [comment]
@mwalbeck I think this is what you were asking for?

![image](https://user-images.githubusercontent.com/1768054/55183921-e870e800-515e-11e9-980d-a7127c87d9d1.png)

**Comment by rcdailey** [comment]
Ah, if I disable the Accessibility app/plugin, that fixes the issue.

Maybe this plugin should work with it enabled, and just override the user's CSS instead of assuming only the server CSS is present?

**Comment by mwalbeck** [comment]
Great find, it seems if you have enabled either the high contrast theme or the dyslexia font from the accessibility app, together with this theme you see this issue.

One of the reason why I haven't enforced the theme styling more heavily is to allow the theming app to work and even the Custom CSS app. 

Do you have a specific use case where you use either the high contrast theme or the dyslexia font with this theme?

**Comment by rcdailey** [comment]
I don't personally. But I could see it mattering to users with actual
disabilities. I have a super simple use case. I only have 2 users.

**Comment by mwalbeck** [comment]
Indeed and I should be easily able to accommodate the dyslexia font, but having a high contrast version that you can turn on/off might not be possible but I'll have to check.

What I can do is to make the theme itself more accessible in general when it comes to color and contrast. If there are any users there might benefit from it. So I'll open a new issue for that specific topic and probably have a look at that for NC 16 as it's probably going to be a big change.

@HydrexHD does disabling the High Contrast theme under accessibility options fix the issue for you?

**Comment by HydrexHD** [comment]
I fix it by disabling the High Contrast theme.

**Comment by mwalbeck** [comment]
Great @HydrexHD I removed your second screenshot as your domain was still visible.
