### ISSUE TITLE
Theming Registration app 'Register' button

### ISSUE THREAD

**Issue by 1aTa** [mwalbeck/nextcloud-breeze-dark#56]
Registration app: https://apps.nextcloud.com/apps/registration

I had to tweak the css to make the 'Register' button match the 'Log in' button.

Would be great if you could include in future versions and not sure if there is a better way of applying the css instead of using !important.

#alternative-logins li a {
  border: 1px solid #706f6e !important;
  background-color: #232629 !important;
  color: #fcfcfc !important;
}
#alternative-logins li a:hover {
  border-color: #3daee9 !important;
  background-color: #1d99f3 !important;
}

**Comment by mwalbeck** [comment]
Thanks for reporting, fix will be included in the next release
