### ISSUE TITLE
Styling for Mindmap app

### ISSUE THREAD

**Issue by riparise** [mwalbeck/nextcloud-breeze-dark#58]
Thanks for this nice theme! Could you please add support for the Mindmap app?
https://apps.nextcloud.com/apps/files_mindmap

**Comment by mwalbeck** [comment]
Thank you for using the theme. NC16 should be out in about a weeks time so when I'm finished with updating the styling for the new release, I'll have a look.

**Comment by mwalbeck** [comment]
I have taken a look at the mindmap app and everything is loaded in an iframe, which means I can't really do any styling to it, with the current functionality of nextcloud theming.

**Comment by riparise** [comment]
Ok, thank you for your time!
