### ISSUE TITLE
Theming on Nextcloud Snap 

### ISSUE THREAD

**Issue by eeickmeyer** [mwalbeck/nextcloud-breeze-dark#62]
Hi! Great job on the theme!

Just thought I'd show you that somebody posted a workaround for theming using the snap version (last comment): https://github.com/nextcloud/nextcloud-snap/issues/915

I just confirmed that it works with your theme. :)

With that, you could probably update your README with this info for others. It's a little hacky, but it's the only known workaround for theming the snap version (which I use).

**Comment by mwalbeck** [comment]
Thanks for letting me know, I have updated the README.
