### ISSUE TITLE
We moved to css variables

### ISSUE THREAD

**Issue by skjnldsv** [mwalbeck/nextcloud-breeze-dark#63]
Hey! :)
I just found your awesome repo! Thanks for helping making Nextcloud awesome!

A few releases back (15 iirc) we added css variables support (simultaneously as dark and accessibility themes)

Instead of using your specific per apps css, you should be able to just change a few variables and see the whole nextcloud change.

Like we do with the dark theme for example: https://github.com/nextcloud/server/blob/d013ff6cae7e01f5a7e3003cde064854922297b4/apps/accessibility/css/themedark.scss
https://github.com/nextcloud/server/blob/d013ff6cae7e01f5a7e3003cde064854922297b4/core/css/css-variables.scss

It should really ease your upgrade path over the following release and hopefully lower the work to do. Alongside the css4 vars implementation, we also upgraded all our supported apps to go with it. But some other apps might still be using  hardcoded variables,so in that case you'll still have to go the old way :)

**Comment by mwalbeck** [comment]
Hi,

I appreciate the kind words, and likewise, Nextcloud is absolutely brilliant.

I did actually play with css variables when you first implemented them, but at that time there were still a lot of apps with hardcoded colours, so I didn't spend too much time on it. I guess I just forgot to revisit it and spend the time to properly implement them in my theme.

So I appreciate the heads up and the links, as you say, it should definitely make it easier to upgrade in the future. I'll have a proper look at it for NC17.

Cheers! Keep up the good work.

**Comment by mwalbeck** [comment]
I have more or less transitioned everything to css variables, both colours and icons. I still need my per app css for most apps, mainly to achieve the look I want. The good news is that I don't have to edit them that often and when I do, it's mainly to remove redundant styling. From NC16->NC17 about 600 lines of css have been removed.

Cheers!
