### ISSUE TITLE
Is there an easy way to change the main colors?

### ISSUE THREAD

**Issue by tiotrom** [mwalbeck/nextcloud-breeze-dark#74]
First, thank you very much for this.
Second, is there an easy way to change the main "blue" color for example? And the background color? Cheers!

**Comment by mwalbeck** [comment]
I'm glad you like it.

Yes there is. If you take a look at the [_colour-variables.scss](https://github.com/mwalbeck/nextcloud-breeze-dark/blob/master/core/css/core/_colour-variables.scss) file, then all the colours I use are defined there. You can simple change the colour value of the colour variables and then recompile server.scss, found in the css folder, into server.css.

If you don't want to play around with sass you can also do a search and replace in server.css.

If you have any further question, let me know.

**Comment by tiotrom** [comment]
Thank you!
