### ISSUE TITLE
Quicknotes delete icon NC15

### ISSUE THREAD

**Issue by molacour** [mwalbeck/nextcloud-breeze-dark#75]
Hi,

the delete icon does not seem to load in Quicknotes, either on HEAD nor NC15 branch.
I tried to run occ commands maintenance:theme:update and maintenance:repair, but still no icon even though I can see it in the img/ folder now.
Also tried to disable Theming app without success.

Any idea?

Thanks!

**Comment by mwalbeck** [comment]
Hi,

Thanks for letting me know.

I'm pretty sure it's just quicknotes that have changed how they handle their icons. I've published a fix in the 15 branch, with a fix for 17 being included in the next release.
