### ISSUE TITLE
Only the default favicon is used.

### ISSUE THREAD

**Issue by tanghus** [mwalbeck/nextcloud-breeze-dark#76]
Each app normally has its own [favicon](https://en.wikipedia.org/wiki/Favicon), but when enabling the theme, only the standard icon is used. As I use several pinned tabs with Firefox, it's impossible to tell them apart.

Theme: 17.0.0
Nextcloud: 17.0.1

**Comment by mwalbeck** [comment]
I've done a little testing and this is very much possible and easy to accomplish. It would be a help if you could tell me which apps you use that have their own favicon, so I don't miss any.

**Comment by tanghus** [comment]
Sweet! 

From the top of my head: files, calendar, contacts, tasks, news, gallery, bookmarks, notes, activity, talk, social, deck....

Maybe it would be easier, if I give notice if I find an app, that doesn't have its own icon? ;)

**Comment by tanghus** [comment]
Hov, du er jo dansker. Hej :wave:

**Comment by mwalbeck** [comment]
Haha, dav dav.

Yeah that might be easier, I'll go through the list of apps that I have styling for and add favicons for those. It was mainly if you use any apps that are outside the general Nextcloud suite.

I do want to note, that files, activity, gallery and possible some others don't have their own favicon at this time, though for those 3, I'm considering adding one myself.

**Comment by tanghus** [comment]
> I do want to note, that files, activity, gallery and possible some others don't have their own favicon at this time, though for those 3, I'm considering adding one myself.

Do you mean in the standard installation, without any themes?

**Comment by mwalbeck** [comment]
Yeah, I'm using images/favicons from upstream and changing the colours to fit.

I have a very limited inkscape skill set so I can only take on simple tasks. Luckily, creating a favicon that's consistent with the rest of the nextcloud favicons should be fairly simple.

**Comment by mwalbeck** [comment]
Everything went fairly smooth so I managed to add favicons for a bunch of apps. You can check them out in the newest release. These are the once that have custom favicons:

* activity
* announcementcenter
* audioplayer
* bookmarks
* calendar
* circles
* contacts
* deck
* files
* forms
* gallery
* mail
* maps
* music
* news
* notes
* ocsms
* passman
* passwords
* polls
* quicknotes
* radio
* social
* spreed
* tasks
* weather

If there are any missing, just open another issue and I'll add them.

**Comment by tanghus** [comment]
Yay \o/ - Dang, that was fast :)

**Comment by mwalbeck** [comment]
As the theme is switching over to a nextcloud app, and I can't find a way to customize global favicons, I've made a custom branch with a theme that only contains favicons. This can be used together with the new app version of the theme.

The branch is just called favicons.

**Comment by tanghus** [comment]
Good idea with an app. So to get full benefit I should use both?

**Comment by mwalbeck** [comment]
It more or less boils down to the questions of whether you want the blue and white favicons that come with nextcloud or grey and blue favicons. I'm pretty sure the default once also have individual favicons for most apps. So it's pretty much personal preference.

**Comment by tanghus** [comment]
I will have to test when I get there then. I really like your theme, so I will definitely install the app if the current solution becomes incompatible with future NC versions.
