### ISSUE TITLE
Grey Text Color is too dark for bigger and newer files

### ISSUE THREAD

**Issue by itsyshaus** [mwalbeck/nextcloud-breeze-dark#78]
If we have an older file on the overview page, for example 2 weeks old, the text gets darker, because the file is older, but this color is too dark. 
Can we fix this?

**Comment by mwalbeck** [comment]
Thanks for reporting this issue.

I can't seem to reproduce your issue, can I get you to share a screenshot?

Also could you tell me which version of Nextcloud you are using?

**Comment by itsyshaus** [comment]
Version 17.0.1

![image](https://user-images.githubusercontent.com/28399213/72046271-533b7c00-32b8-11ea-8575-a1c232fa885e.png)

**Comment by mwalbeck** [comment]
I think I've figured out why I was a bit confused. The dark theme you are using is the one built into Nextcloud. For bugs regarding that, you should head over to this repo https://github.com/nextcloud/server/

I'm the developer of this dark theme, https://apps.nextcloud.com/apps/breezedark

Though I had a quick look and it seems it might just be a caching issue. Try and press Ctrl + F5 while on the page or try opening a incognito/private window and see if that doesn't fix it.
