### ISSUE TITLE
How to activate the blue Icons?

### ISSUE THREAD

**Issue by KoljaL** [mwalbeck/nextcloud-breeze-dark#79]
Great dark Theme!

But how can i activate these blue Icons for the header menue?
https://github.com/mwalbeck/nextcloud-breeze-dark/blob/master/apps/notes/img/favicon-touch.png

**Comment by mwalbeck** [comment]
Those icons are for the small icons in your browser tabs. I haven't found a way use that functionality with the app version of the theme. To work around it I have made a secondary theme, using the old method, that include only the favicons. 

It's in this same repo, just under the branch favicons. You can check it out here https://github.com/mwalbeck/nextcloud-breeze-dark/tree/favicons

**Comment by mwalbeck** [comment]
If you have any more questions let me know.
