### ISSUE TITLE
Update theme for NC18

### ISSUE THREAD

**Issue by mwalbeck** [mwalbeck/nextcloud-breeze-dark#80]
- [x] Core
- [x] Calendar
- [x] Contacts
- [x] Activity
- [x] Photos
- [x] Talk
- [x] Mail
- [x] Tasks
- [x] Deck
- [x] News
- [x] Group folders
- [x] Notes
- [x] Workflow

**Comment by metaMMA** [comment]
I loved using this theme on NC17. Looking forward to the v18+ release. Thanks, again!

**Comment by mwalbeck** [comment]
The first release for NC18 has just been published on the Nextcloud app store
