### ISSUE TITLE
maps right click not themed

### ISSUE THREAD

**Issue by geeseven** [mwalbeck/nextcloud-breeze-dark#84]
Greetings,

The right click menu on the map in [nextcloud/maps][0] is not themed correctly.  White background with light grey text and black icons.  On the other hand, the left click menu is themed correctly.

Nextcloud: 17.0.3
maps: 0.1.4
Breeze Dark: 17.0.5

Thanks for the great theme. 

[0]: https://github.com/nextcloud/maps

**Comment by mwalbeck** [comment]
Thanks for reporting this. I'll have a look and get it fixed for the next release.

I can see there are a few other issue with the Maps app, that I'll also have a look at while I'm at it.

**Comment by mwalbeck** [comment]
Thanks again for reporting the issue, It has now been fixed. There are still a few icons that I would like to improve the visibility of, but they are currently hardcoded in the html, so there isn't much I can do for now.
