### ISSUE TITLE
Choose as profile picture not themed

### ISSUE THREAD

**Issue by geeseven** [mwalbeck/nextcloud-breeze-dark#85]
Hey @mwalbeck,

I found another section that is not themed correctly.  When selecting a profile picture, there is a confirmation 'pop up' that is not themed.  The steps to reproduce are user (icon in the top right) -> Settings -> Personal info then click upload or folder icon -> select an image then the 'pop up' will be displayed.

**Comment by mwalbeck** [comment]
Thanks, all fixed in the latest release.
