### ISSUE TITLE
Poll font/background color

### ISSUE THREAD

**Issue by ToneLune** [mwalbeck/nextcloud-breeze-dark#88]
Hello, 

In the Poll application, by consulting a public link, the color of the font cannot be read on the green or red background of the upper banner.

In pictures:
![Image 1](https://user-images.githubusercontent.com/12959697/73700788-cbdefe00-46e7-11ea-8c56-fb54e3a86109.png)

![Image 2](https://user-images.githubusercontent.com/12959697/73700790-cbdefe00-46e7-11ea-8fcd-b63c948a8a14.png)

Thank you !

**Comment by mwalbeck** [comment]
Thanks for reporting this, I'll have a look and get it fixed.

**Comment by mwalbeck** [comment]
This should be fixed in 18.0.4. Thanks again for reporting.

**Comment by ToneLune** [comment]
Hello!

Thanks, but it didn't solve after 18.0.4 update. :)

**Comment by mwalbeck** [comment]
Have you cleared your browser cache or done a Ctrl+F5 on the page?
