### ISSUE TITLE
Terms of service app not readable

### ISSUE THREAD

**Issue by SuperSandro2000** [mwalbeck/nextcloud-breeze-dark#91]
![image](https://user-images.githubusercontent.com/7258858/74092936-76319980-4acb-11ea-9352-d3087a5ae140.png)

highlighted with cursor

![image](https://user-images.githubusercontent.com/7258858/74092933-6ade6e00-4acb-11ea-9171-50744ee9aafa.png)

Source: https://github.com/nextcloud/terms_of_service/

**Comment by mwalbeck** [comment]
Thanks for reporting this, I'll have a look and get it fixed.

**Comment by mwalbeck** [comment]
Thanks again for reporting this. It should be fixed in the latest release. Let me know if you have any problems with it.

Cheers!
