### ISSUE TITLE
Fix Styling for Two-Factor TOTP Provider

### ISSUE THREAD

**Issue by mwarth** [mwalbeck/nextcloud-breeze-dark#95]
**Which app would you like to have styled**:
Two-Factor TOTP Provider

**Your setup (please complete the following information):**
 - Nextcloud version: 18.0

I read on #2 that the Two-Factor TOTP Provider App is styled but actually the submit button isn't dark (maybe it has been changed recently)
![image](https://user-images.githubusercontent.com/30124114/74312393-ed885700-4d71-11ea-90ea-1423b102bdde.png)

**Comment by mwalbeck** [comment]
Thanks for reporting this. I must admit, I probably just forgot to verify it was styled probably during the last big transition phase. I'll get it fixed for the next release.

**Comment by mwalbeck** [comment]
Thanks again for reporting this. There is a fix included in the latest release.

Cheers!
