### ISSUE TITLE
Fix styling for routing dialogue in Maps

### ISSUE THREAD

**Issue by manuquadrat** [mwalbeck/nextcloud-breeze-dark#96]
**Which app would you like to have styled**:
Nextcloud Maps Routing Dialogue

**Your setup (please complete the following information):**
 - Nextcloud version: 17.0.2

The routing dialogue (in this case with mapbox) seems not to be handled correctly in the theme (as can be seen in the picture attached)
![Maps Routing](https://user-images.githubusercontent.com/61155531/74668368-5ffb9b80-51a5-11ea-989e-15ea22cb0f5f.png)

**Comment by mwalbeck** [comment]
Thanks for reporting this, seems like it broke with the latest maps release. I'll have a look and get it fixed

**Comment by mwalbeck** [comment]
This has been fixed in the latest NC17 release. A fix for NC18 will be coming a bit later.
